from typing import Dict, List

class NextJSGenerator:
    """
    Generates Next.js application code.
    """
    
    def generate_project_structure(self, project_name: str) -> Dict[str, str]:
        """
        Returns a dictionary representing the file structure of a Next.js app.
        Keys are file paths, values are file contents (or descriptions).
        """
        structure = {
            f"{project_name}/package.json": self._generate_package_json(project_name),
            f"{project_name}/tsconfig.json": self._generate_tsconfig(),
            f"{project_name}/next.config.js": "module.exports = { reactStrictMode: true }",
            f"{project_name}/app/layout.tsx": self._generate_layout(),
            f"{project_name}/app/page.tsx": self.generate_page("Home", "/"),
            f"{project_name}/components/ui/button.tsx": self._generate_button_component(),
        }
        return structure

    def generate_page(self, prompt: str, route: str) -> str:
        """
        Generates a Next.js page component.
        """
        component_name = "Page"
        title = prompt.capitalize()
        
        return f"""import React from 'react';

export default function {component_name}() {{
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">
        <h1 className="text-4xl font-bold">{title}</h1>
        <p>Generated based on: {prompt}</p>
      </div>
    </main>
  );
}}
"""

    def generate_component(self, prompt: str, name: str) -> str:
        """
        Generates a React component.
        """
        return f"""import React from 'react';

interface {name}Props {{
  children: React.ReactNode;
}}

export const {name}: React.FC<{name}Props> = ({{ children }}) => {{
  return (
    <div className="p-4 border rounded-lg shadow-sm">
      <h2 className="text-xl font-semibold mb-2">{name}</h2>
      {{children}}
    </div>
  );
}};
"""

    def _generate_package_json(self, name: str) -> str:
        return f"""{{
  "name": "{name}",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  }},
  "dependencies": {{
    "react": "^18",
    "react-dom": "^18",
    "next": "14.0.0"
  }},
  "devDependencies": {{
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "tailwindcss": "^3",
    "postcss": "^8"
  }}
}}"""

    def _generate_tsconfig(self) -> str:
        return """{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}"""

    def _generate_layout(self) -> str:
        return """import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by Web Gen System',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}"""

    def _generate_button_component(self) -> str:
        return """import * as React from "react"

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement> {}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, ...props }, ref) => {
    return (
      <button
        className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2"
        ref={ref}
        {...props}
      />
    )
  }
)
Button.displayName = "Button"

export { Button }
"""
