"""
Constants - Constantes del Sistema
===================================

Constantes centralizadas para evitar valores mágicos en el código.
"""

# Timeouts
DEFAULT_TASK_TIMEOUT = 300.0
DEFAULT_COMMAND_TIMEOUT = 300.0
DEFAULT_WEBSOCKET_TIMEOUT = 300.0
DEFAULT_HTTP_TIMEOUT = 30.0

# Límites
MAX_COMMAND_LENGTH = 10000
MAX_RESPONSE_SIZE = 10 * 1024 * 1024  # 10MB
MAX_CACHE_SIZE = 1000
MAX_CONCURRENT_TASKS = 5
MAX_WEBSOCKET_CONNECTIONS = 100

# Intervalos
DEFAULT_CHECK_INTERVAL = 1.0
DEFAULT_CLEANUP_INTERVAL = 300.0
DEFAULT_HEARTBEAT_INTERVAL = 30.0

# Rate Limiting
DEFAULT_RATE_LIMIT_MAX_REQUESTS = 100
DEFAULT_RATE_LIMIT_WINDOW_SECONDS = 60
DEFAULT_USER_RATE_LIMIT_MAX_REQUESTS = 50

# Circuit Breaker
DEFAULT_CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5
DEFAULT_CIRCUIT_BREAKER_RECOVERY_TIMEOUT = 60.0

# Cache
DEFAULT_CACHE_TTL = 300.0
DEFAULT_COMMAND_CACHE_TTL = 3600.0

# Retry
DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_DELAY = 1.0
DEFAULT_RETRY_BACKOFF = 2.0

# Security
MAX_URL_LENGTH = 2048
SENSITIVE_ENV_VARS = ['API_KEY', 'SECRET', 'PASSWORD', 'TOKEN', 'CREDENTIAL']

# File Paths
DEFAULT_STORAGE_PATH = "./data/agent_state.json"
DEFAULT_LOG_DIR = "./logs"

# API Versions
API_VERSION = "v1"
MCP_API_VERSION = "v1"

# Status Codes
HTTP_OK = 200
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_ERROR = 500

