import { createShapeId, TLShapeId } from '@tldraw/tldraw';
import { Presentation, FileText, Image, Layout, Table, BarChart, PieChart, LineChart, Calendar, List, CheckSquare, MessageSquare } from 'lucide-react';

export interface TemplateShape {
  id: TLShapeId;
  type: 'rectangle' | 'text' | 'image' | 'line' | 'arrow' | 'frame' | 'geo';
  x: number;
  y: number;
  width?: number;
  height?: number;
  text?: string;
  rotation: number;
  style: {
    color: string;
    fill?: string;
    size?: string;
    dash?: string;
    opacity?: number;
  };
  isLocked: boolean;
  parentId: string;
  index: string;
  opacity?: number;
  props?: Record<string, unknown>;
  meta?: Record<string, unknown>;
  typeName: string;
}

export interface Template {
  id: string;
  name: string;
  icon: typeof Presentation;
  category: 'presentation' | 'document' | 'design' | 'data' | 'planning';
  description: string;
  shapes: TemplateShape[];
}

export const templates: Template[] = [
  {
    id: 'presentation',
    name: 'Presentación',
    icon: Presentation,
    category: 'presentation',
    description: 'Plantilla para crear presentaciones profesionales',
    shapes: [
      {
        id: createShapeId(),
        type: 'rectangle',
        typeName: 'rectangle',
        x: 100,
        y: 100,
        width: 800,
        height: 600,
        rotation: 0,
        style: { color: 'white', fill: 'white' },
        isLocked: false,
        parentId: 'page',
        index: 'a1',
        opacity: 1,
        props: {},
        meta: {},
      },
      {
        id: createShapeId(),
        type: 'text',
        typeName: 'text',
        x: 150,
        y: 150,
        text: 'Título de la Presentación',
        rotation: 0,
        style: { color: 'black', size: 'l' },
        isLocked: false,
        parentId: 'page',
        index: 'a2',
        opacity: 1,
        props: {},
        meta: {},
      },
    ],
  },
  {
    id: 'document',
    name: 'Documento',
    icon: FileText,
    category: 'document',
    description: 'Plantilla para documentos formales',
    shapes: [
      {
        id: createShapeId(),
        type: 'rectangle',
        typeName: 'rectangle',
        x: 100,
        y: 100,
        width: 600,
        height: 800,
        rotation: 0,
        style: { color: 'white', fill: 'white' },
        isLocked: false,
        parentId: 'page',
        index: 'a1',
        opacity: 1,
        props: {},
        meta: {},
      },
      {
        id: createShapeId(),
        type: 'text',
        typeName: 'text',
        x: 150,
        y: 150,
        text: 'Título del Documento',
        rotation: 0,
        style: { color: 'black', size: 'l' },
        isLocked: false,
        parentId: 'page',
        index: 'a2',
        opacity: 1,
        props: {},
        meta: {},
      },
    ],
  },
  {
    id: 'design',
    name: 'Diseño',
    icon: Image,
    category: 'design',
    description: 'Plantilla para diseños creativos',
    shapes: [
      {
        id: createShapeId(),
        type: 'rectangle',
        typeName: 'rectangle',
        x: 100,
        y: 100,
        width: 1000,
        height: 800,
        rotation: 0,
        style: { color: 'white', fill: 'white' },
        isLocked: false,
        parentId: 'page',
        index: 'a1',
        opacity: 1,
        props: {},
        meta: {},
      },
      {
        id: createShapeId(),
        type: 'text',
        typeName: 'text',
        x: 150,
        y: 150,
        text: 'Diseño',
        rotation: 0,
        style: { color: 'black', size: 'l' },
        isLocked: false,
        parentId: 'page',
        index: 'a2',
        opacity: 1,
        props: {},
        meta: {},
      },
    ],
  },
  {
    id: 'dashboard',
    name: 'Dashboard',
    icon: Layout,
    category: 'data',
    description: 'Plantilla para dashboards y visualizaciones',
    shapes: [
      {
        id: createShapeId(),
        type: 'rectangle',
        typeName: 'rectangle',
        x: 100,
        y: 100,
        width: 1200,
        height: 800,
        rotation: 0,
        style: { color: 'white', fill: 'white' },
        isLocked: false,
        parentId: 'page',
        index: 'a1',
        opacity: 1,
        props: {},
        meta: {},
      },
      {
        id: createShapeId(),
        type: 'text',
        typeName: 'text',
        x: 150,
        y: 150,
        text: 'Dashboard',
        rotation: 0,
        style: { color: 'black', size: 'l' },
        isLocked: false,
        parentId: 'page',
        index: 'a2',
        opacity: 1,
        props: {},
        meta: {},
      },
    ],
  },
  {
    id: 'kanban',
    name: 'Kanban',
    icon: Table,
    category: 'planning',
    description: 'Plantilla para gestión de proyectos',
    shapes: [
      {
        id: createShapeId(),
        type: 'rectangle',
        typeName: 'rectangle',
        x: 100,
        y: 100,
        width: 1200,
        height: 800,
        rotation: 0,
        style: { color: 'white', fill: 'white' },
        isLocked: false,
        parentId: 'page',
        index: 'a1',
        opacity: 1,
        props: {},
        meta: {},
      },
      {
        id: createShapeId(),
        type: 'text',
        typeName: 'text',
        x: 150,
        y: 150,
        text: 'Kanban Board',
        rotation: 0,
        style: { color: 'black', size: 'l' },
        isLocked: false,
        parentId: 'page',
        index: 'a2',
        opacity: 1,
        props: {},
        meta: {},
      },
    ],
  },
  {
    id: 'chart',
    name: 'Gráficos',
    icon: BarChart,
    category: 'data',
    description: 'Plantilla para visualización de datos',
    shapes: [
      {
        id: createShapeId(),
        type: 'rectangle',
        typeName: 'rectangle',
        x: 100,
        y: 100,
        width: 800,
        height: 600,
        rotation: 0,
        style: { color: 'white', fill: 'white' },
        isLocked: false,
        parentId: 'page',
        index: 'a1',
        opacity: 1,
        props: {},
        meta: {},
      },
      {
        id: createShapeId(),
        type: 'text',
        typeName: 'text',
        x: 150,
        y: 150,
        text: 'Gráficos',
        rotation: 0,
        style: { color: 'black', size: 'l' },
        isLocked: false,
        parentId: 'page',
        index: 'a2',
        opacity: 1,
        props: {},
        meta: {},
      },
    ],
  },
  {
    id: 'mindmap',
    name: 'Mapa Mental',
    icon: PieChart,
    category: 'planning',
    description: 'Plantilla para mapas mentales',
    shapes: [
      {
        id: createShapeId(),
        type: 'rectangle',
        typeName: 'rectangle',
        x: 100,
        y: 100,
        width: 1000,
        height: 800,
        rotation: 0,
        style: { color: 'white', fill: 'white' },
        isLocked: false,
        parentId: 'page',
        index: 'a1',
        opacity: 1,
        props: {},
        meta: {},
      },
      {
        id: createShapeId(),
        type: 'text',
        typeName: 'text',
        x: 150,
        y: 150,
        text: 'Mapa Mental',
        rotation: 0,
        style: { color: 'black', size: 'l' },
        isLocked: false,
        parentId: 'page',
        index: 'a2',
        opacity: 1,
        props: {},
        meta: {},
      },
    ],
  },
  {
    id: 'timeline',
    name: 'Línea de Tiempo',
    icon: LineChart,
    category: 'planning',
    description: 'Plantilla para líneas de tiempo',
    shapes: [
      {
        id: createShapeId(),
        type: 'rectangle',
        typeName: 'rectangle',
        x: 100,
        y: 100,
        width: 1200,
        height: 600,
        rotation: 0,
        style: { color: 'white', fill: 'white' },
        isLocked: false,
        parentId: 'page',
        index: 'a1',
        opacity: 1,
        props: {},
        meta: {},
      },
      {
        id: createShapeId(),
        type: 'text',
        typeName: 'text',
        x: 150,
        y: 150,
        text: 'Línea de Tiempo',
        rotation: 0,
        style: { color: 'black', size: 'l' },
        isLocked: false,
        parentId: 'page',
        index: 'a2',
        opacity: 1,
        props: {},
        meta: {},
      },
    ],
  },
  {
    id: 'calendar',
    name: 'Calendario',
    icon: Calendar,
    category: 'planning',
    description: 'Plantilla para calendarios',
    shapes: [
      {
        id: createShapeId(),
        type: 'rectangle',
        typeName: 'rectangle',
        x: 100,
        y: 100,
        width: 800,
        height: 600,
        rotation: 0,
        style: { color: 'white', fill: 'white' },
        isLocked: false,
        parentId: 'page',
        index: 'a1',
        opacity: 1,
        props: {},
        meta: {},
      },
      {
        id: createShapeId(),
        type: 'text',
        typeName: 'text',
        x: 150,
        y: 150,
        text: 'Calendario',
        rotation: 0,
        style: { color: 'black', size: 'l' },
        isLocked: false,
        parentId: 'page',
        index: 'a2',
        opacity: 1,
        props: {},
        meta: {},
      },
    ],
  },
  {
    id: 'checklist',
    name: 'Lista de Tareas',
    icon: CheckSquare,
    category: 'planning',
    description: 'Plantilla para listas de tareas',
    shapes: [
      {
        id: createShapeId(),
        type: 'rectangle',
        typeName: 'rectangle',
        x: 100,
        y: 100,
        width: 600,
        height: 800,
        rotation: 0,
        style: { color: 'white', fill: 'white' },
        isLocked: false,
        parentId: 'page',
        index: 'a1',
        opacity: 1,
        props: {},
        meta: {},
      },
      {
        id: createShapeId(),
        type: 'text',
        typeName: 'text',
        x: 150,
        y: 150,
        text: 'Lista de Tareas',
        rotation: 0,
        style: { color: 'black', size: 'l' },
        isLocked: false,
        parentId: 'page',
        index: 'a2',
        opacity: 1,
        props: {},
        meta: {},
      },
    ],
  },
  {
    id: 'chat',
    name: 'Chat',
    icon: MessageSquare,
    category: 'design',
    description: 'Plantilla para interfaces de chat',
    shapes: [
      {
        id: createShapeId(),
        type: 'rectangle',
        typeName: 'rectangle',
        x: 100,
        y: 100,
        width: 400,
        height: 800,
        rotation: 0,
        style: { color: 'white', fill: 'white' },
        isLocked: false,
        parentId: 'page',
        index: 'a1',
        opacity: 1,
        props: {},
        meta: {},
      },
      {
        id: createShapeId(),
        type: 'text',
        typeName: 'text',
        x: 150,
        y: 150,
        text: 'Chat',
        rotation: 0,
        style: { color: 'black', size: 'l' },
        isLocked: false,
        parentId: 'page',
        index: 'a2',
        opacity: 1,
        props: {},
        meta: {},
      },
    ],
  },
  {
    id: 'diapositivas',
    name: 'Diapositivas',
    icon: Presentation,
    category: 'presentation',
    description: 'Plantilla inspirada en Clean Zine, ideal para presentaciones minimalistas.',
    shapes: [
      {
        id: createShapeId(),
        type: 'geo',
        typeName: 'geo',
        x: 0,
        y: 0,
        rotation: 0,
        isLocked: false,
        parentId: 'page',
        index: 'a1',
        opacity: 1,
        style: {
          color: 'black',
          fill: 'blue',
          size: 'm',
          dash: 'solid',
        },
        props: {
          geo: 'rectangle',
          w: 900,
          h: 500,
        },
        meta: {},
      },
      {
        id: createShapeId(),
        type: 'text',
        typeName: 'text',
        x: 80,
        y: 80,
        width: 600,
        height: 120,
        text: 'DIAPOSITIVAS\nTEMA',
        rotation: 0,
        style: {
          color: '#6B4F2B',
          size: 'xl',
        },
        isLocked: false,
        parentId: 'page',
        index: 'a2',
        opacity: 1,
        props: {},
        meta: {},
      },
      {
        id: createShapeId(),
        type: 'text',
        typeName: 'text',
        x: 100,
        y: 220,
        width: 300,
        height: 40,
        text: 'Fecha de Presentación',
        rotation: 0,
        style: {
          color: '#6B4F2B',
          size: 'm',
        },
        isLocked: false,
        parentId: 'page',
        index: 'a3',
        opacity: 1,
        props: {},
        meta: {},
      },
      {
        id: createShapeId(),
        type: 'image',
        typeName: 'image',
        x: 120,
        y: 280,
        width: 180,
        height: 120,
        rotation: 0,
        style: {
          color: '#ffffff',
        },
        isLocked: false,
        parentId: 'page',
        index: 'a4',
        opacity: 1,
        props: {
          url: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
        },
        meta: {},
      },
    ],
  },
]; 