"""
Constants - Shared constants for bulk processing
===============================================

Centralized constants used across bulk processing modules.
"""

MAX_DOCUMENTS_LIMIT = 10000
MIN_DOCUMENTS = 1
MAX_DOCUMENT_TYPES = 50
MAX_BUSINESS_AREAS = 50
MIN_QUERY_LENGTH = 3
MAX_QUERY_LENGTH = 10000
MAX_DOCUMENT_TYPE_LENGTH = 100
MAX_BUSINESS_AREA_LENGTH = 100

MIN_PRIORITY = 1
MAX_PRIORITY = 5

DEFAULT_MAX_DOCUMENTS = 100
DEFAULT_PRIORITY = 1
DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_DELAY_BASE = 1.0
ENHANCED_RETRY_DELAY_BASE = 2.0
MAX_RETRY_DELAY = 60

# Processing Loop
DEFAULT_LOOP_SLEEP_SECONDS = 0.1  # Sleep interval in processing loops

MIN_QUALITY_SCORE = 0.0
MAX_QUALITY_SCORE = 1.0
DEFAULT_QUALITY_THRESHOLD = 0.85

TASK_STATUS_PENDING = "pending"
TASK_STATUS_PROCESSING = "processing"
TASK_STATUS_COMPLETED = "completed"
TASK_STATUS_FAILED = "failed"

REQUEST_STATUS_ACTIVE = "active"
REQUEST_STATUS_COMPLETED = "completed"

