apiVersion: v1
kind: Service
metadata:
  name: bul-api-service
  labels:
    app: bul-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: bul-api
































