# Production Configuration for Ultra-Optimized SEO Service
# Environment: Production
# Version: 2.0.0

app:
  name: "SEO Service Ultra-Optimized"
  version: "2.0.0"
  environment: "production"
  debug: false
  log_level: "INFO"

server:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 30
  max_requests: 10000
  max_requests_jitter: 1000
  keepalive: 5
  keepalive_connections: 100

database:
  url: "postgresql://seo_user:${DB_PASSWORD}@postgres:5432/seo_db"
  pool_size: 20
  max_overflow: 30
  pool_timeout: 30
  pool_recycle: 3600
  echo: false
  ssl_mode: "require"

redis:
  url: "redis://${REDIS_PASSWORD}@redis:6379/0"
  password: "${REDIS_PASSWORD}"
  db: 0
  max_connections: 50
  socket_timeout: 5
  socket_connect_timeout: 5
  retry_on_timeout: true
  health_check_interval: 30

openai:
  api_key: "${OPENAI_API_KEY}"
  model: "gpt-4-turbo-preview"
  temperature: 0.1
  max_tokens: 4000
  request_timeout: 30
  max_retries: 3
  retry_delay: 1

selenium:
  headless: true
  timeout: 30
  window_size: "1920x1080"
  user_agent: "SEO-Bot/2.0 (Ultra-Optimized)"
  no_sandbox: true
  disable_dev_shm_usage: true
  disable_gpu: true
  disable_web_security: true
  disable_images: true
  disable_javascript: false
  page_load_strategy: "eager"

parser:
  type: "selectolax"
  fallback: "lxml"
  timeout: 10.0
  max_size: "50MB"
  enable_compression: true
  compression_level: 3
  cache_parsed_data: true
  max_cache_size: 1000

cache:
  type: "ultra_optimized"
  size: 5000
  ttl: 7200
  compression_level: 3
  enable_stats: true
  enable_eviction: true
  eviction_policy: "lru"
  max_memory: "1GB"
  backup_interval: 300

http_client:
  rate_limit: 200
  max_connections: 200
  timeout: 15.0
  enable_http2: true
  retry_attempts: 3
  retry_delay: 1
  max_redirects: 5
  verify_ssl: true
  user_agent: "SEO-Service/2.0"
  default_headers:
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    Accept-Language: "en-US,en;q=0.5"
    Accept-Encoding: "gzip, deflate"
    Connection: "keep-alive"
    Upgrade-Insecure-Requests: "1"

analyzer:
  openai_enabled: true
  langchain_enabled: true
  transformers_enabled: true
  enable_keyword_analysis: true
  enable_sentiment_analysis: true
  enable_readability_analysis: true
  enable_competitor_analysis: true
  max_content_length: 50000
  batch_size: 10
  parallel_analysis: true

security:
  secret_key: "${SECRET_KEY}"
  api_key: "${API_KEY}"
  cors_origins: 
    - "https://yourdomain.com"
    - "https://admin.yourdomain.com"
  cors_credentials: true
  cors_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  cors_headers: ["*"]
  rate_limit_enabled: true
  rate_limit_requests: 100
  rate_limit_window: 60
  rate_limit_by_ip: true
  ip_whitelist: []
  ip_blacklist: []

monitoring:
  prometheus_port: 9090
  grafana_port: 3000
  health_check_interval: 30
  metrics_enabled: true
  tracing_enabled: true
  profiling_enabled: false
  alerting_enabled: true
  alert_thresholds:
    error_rate: 0.05
    response_time: 2.0
    memory_usage: 0.8
    cpu_usage: 0.8

logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
  file_enabled: true
  file_path: "logs/seo-service.log"
  rotation: "100 MB"
  retention: "30 days"
  compression: "zip"
  json_enabled: true
  json_path: "logs/seo-service.json"
  syslog_enabled: false
  syslog_address: "/dev/log"
  syslog_facility: "local0"

batch_service:
  enabled: true
  max_concurrent: 10
  max_batch_size: 100
  timeout: 300
  retry_attempts: 3
  retry_delay: 5
  queue_size: 1000
  worker_processes: 4

selenium_service:
  enabled: true
  pool_size: 5
  max_instances: 10
  health_check_interval: 60
  restart_failed_instances: true
  max_restart_attempts: 3
  screenshot_enabled: false
  screenshot_path: "screenshots"

performance:
  enable_gzip: true
  gzip_level: 6
  enable_brotli: true
  brotli_quality: 11
  enable_caching: true
  cache_headers:
    - "Cache-Control"
    - "ETag"
    - "Last-Modified"
  static_files_cache: 86400
  api_cache: 300
  enable_compression: true
  compression_threshold: 1024

backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 30
  backup_path: "/backups"
  include_logs: true
  include_config: true
  compression: true
  encryption: false

maintenance:
  enabled: true
  schedule: "0 3 * * 0"  # Weekly on Sunday at 3 AM
  cleanup_old_logs: true
  cleanup_old_cache: true
  cleanup_old_screenshots: true
  vacuum_database: true
  optimize_cache: true

scaling:
  auto_scaling: true
  min_instances: 2
  max_instances: 10
  cpu_threshold: 0.7
  memory_threshold: 0.8
  response_time_threshold: 2.0
  scale_up_cooldown: 300
  scale_down_cooldown: 600

load_balancing:
  enabled: true
  algorithm: "round_robin"
  health_check_path: "/health"
  health_check_interval: 10
  health_check_timeout: 5
  health_check_retries: 3
  sticky_sessions: false
  session_timeout: 3600

circuit_breaker:
  enabled: true
  failure_threshold: 5
  recovery_timeout: 60
  expected_exception: "Exception"
  half_open_state: true
  volume_threshold: 10

retry:
  enabled: true
  max_attempts: 3
  initial_delay: 1
  max_delay: 10
  backoff_factor: 2
  jitter: true

timeouts:
  request: 30
  connect: 10
  read: 20
  write: 20
  idle: 60
  keepalive: 5

limits:
  max_request_size: "10MB"
  max_response_size: "50MB"
  max_connections: 1000
  max_concurrent_requests: 100
  max_memory_usage: "2GB"
  max_cpu_usage: 0.9

optimization:
  enable_async: true
  enable_connection_pooling: true
  enable_compression: true
  enable_caching: true
  enable_batching: true
  enable_streaming: true
  enable_prefetching: true
  enable_lazy_loading: true 