/**
 * README Generator - Generates README files for models
 */

import { toPascalCase, toPascalCaseLoss } from './code-generators'
import type { ModelSpec } from '../core/types'

/**
 * Generate README content for a model
 */
export function generateReadme(
  modelName: string,
  description: string,
  spec: ModelSpec
): string {
  const className = toPascalCase(modelName)

  return `# ${className}

![TruthGPT](https://img.shields.io/badge/TruthGPT-Powered-purple?style=for-the-badge&logo=github)

TruthGPT Model Generated Automatically

## Description

${description}

## Model Specifications

- **Type**: ${spec.type}
- **Architecture**: ${spec.architecture}
- **Layers**: ${spec.layers.join(', ')}
- **Activation**: ${spec.activation}
- **Optimizer**: ${spec.optimizer}
- **Learning Rate**: ${spec.learningRate}
- **Loss Function**: ${spec.loss}
- **Metrics**: ${spec.metrics.join(', ')}

## Installation

\`\`\`bash
pip install -r requirements.txt
\`\`\`

## Usage

\`\`\`python
from ${modelName} import ${className}
import truthgpt as tg
import numpy as np

# Create model instance
model = ${className}()

# Compile model
model.compile(
    optimizer=tg.optimizers.${capitalizeFirst(spec.optimizer)}(learning_rate=${spec.learningRate}),
    loss=tg.losses.${toPascalCaseLoss(spec.loss)}(),
    metrics=['${spec.metrics.join("', '")}']
)

# Prepare your data
# x_train, y_train = your_training_data
# x_test, y_test = your_test_data

# Train model
history = model.fit(x_train, y_train, epochs=${spec.epochs}, batch_size=${spec.batchSize})

# Evaluate model
test_loss, test_accuracy = model.evaluate(x_test, y_test)

# Make predictions
predictions = model.predict(x_test)
\`\`\`

## Model Architecture

${generateArchitectureDescription(spec)}

## Training

This model uses TruthGPT optimizations for improved performance and efficiency.

## License

This model was generated using TruthGPT and is ready for deployment.

## Generated by

TruthGPT Model Builder
`
}

/**
 * Generate architecture description
 */
function generateArchitectureDescription(spec: ModelSpec): string {
  if (spec.architecture === 'cnn') {
    return `- Convolutional Layers with MaxPooling
- Flatten Layer
- Dense Layers with Dropout
- Output Layer with ${spec.outputActivation} activation`
  } else if (spec.architecture === 'lstm') {
    return `- Embedding Layer
- LSTM Layers with Dropout
- Dense Layers
- Output Layer with ${spec.outputActivation} activation`
  } else if (spec.architecture === 'transformer') {
    return `- Embedding Layer
- Transformer Blocks
- Dense Layers with Dropout
- Output Layer with ${spec.outputActivation} activation`
  } else {
    return spec.layers
      .map((size, idx) => {
        const isLast = idx === spec.layers.length - 1
        const activation = isLast ? spec.outputActivation : spec.activation
        return `- Layer ${idx + 1}: Dense(${size}) with ${activation} activation`
      })
      .join('\n')
  }
}


