require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native-unimodules/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

target 'ai-project-generator' do
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end

