# Default Configuration Templates
# =============================
# This file contains default configurations for different model types and use cases

# Diffusion Model Configuration
diffusion_default:
  name: "diffusion_default"
  description: "Default configuration for diffusion-based video generation"
  version: "1.0.0"
  created_at: "2024-01-01T00:00:00"
  
  system:
    environment: "development"
    debug: true
    log_level: "INFO"
    base_dir: "."
    config_dir: "configs"
    output_dir: "outputs"
    logs_dir: "logs"
    num_threads: 4
    memory_limit: null
    gpu_memory_fraction: 0.9
    enable_security: true
    max_file_size: 104857600
    allowed_file_types: [".mp4", ".avi", ".mov"]
  
  model:
    model_type: "diffusion"
    model_name: "diffusion_model"
    version: "1.0.0"
    input_channels: 3
    output_channels: 3
    latent_dim: 512
    hidden_dims: [64, 128, 256, 512]
    num_layers: 4
    dropout_rate: 0.1
    use_batch_norm: true
    activation: "relu"
    frame_size: [256, 256]
    num_frames: 16
    temporal_stride: 1
    fps: 30
    device: "cuda"
    dtype: "float16"
    use_mixed_precision: true
    use_gradient_checkpointing: false
    diffusion_steps: 1000
    noise_schedule: "linear"
    classifier_free_guidance: true
    guidance_scale: 7.5
  
  data:
    data_dir: "data/videos"
    metadata_file: null
    cache_dir: null
    frame_size: [256, 256]
    num_frames: 16
    fps: 30
    channels: 3
    batch_size: 8
    num_workers: 4
    pin_memory: true
    shuffle: true
    drop_last: true
    normalize: true
    normalize_mean: [0.485, 0.456, 0.406]
    normalize_std: [0.229, 0.224, 0.225]
    augment: true
    cache_data: false
    max_cache_size: 1000
    horizontal_flip_prob: 0.5
    vertical_flip_prob: 0.0
    rotation_prob: 0.2
    rotation_degrees: 15.0
    crop_prob: 0.3
    crop_ratio: 0.8
    brightness_jitter: 0.1
    contrast_jitter: 0.1
    saturation_jitter: 0.1
    hue_jitter: 0.05
    train_split: 0.8
    val_split: 0.1
    test_split: 0.1
    random_seed: 42
  
  training:
    num_epochs: 100
    batch_size: 8
    learning_rate: 0.0001
    weight_decay: 0.00001
    gradient_clip: 1.0
    max_grad_norm: 1.0
    optimizer: "adam"
    optimizer_params: {}
    scheduler: "cosine"
    scheduler_params: {}
    loss_type: "mse"
    loss_weights: {}
    save_frequency: 10
    eval_frequency: 5
    log_frequency: 100
    early_stopping_patience: 20
    early_stopping_min_delta: 0.0001
    checkpoint_dir: "checkpoints"
    save_best_only: true
    max_checkpoints: 5
    resume_from_checkpoint: null
    use_wandb: false
    use_tensorboard: true
    experiment_name: "ai_video_training"
    project_name: "ai_video"
    use_amp: true
    use_gradient_accumulation: false
    gradient_accumulation_steps: 1
    use_ddp: false
    local_rank: -1
  
  evaluation:
    batch_size: 8
    num_samples: null
    device: "cuda"
    compute_psnr: true
    compute_ssim: true
    compute_lpips: true
    compute_fid: false
    compute_inception_score: false
    save_results: true
    save_videos: false
    output_dir: "evaluation_results"
    save_format: "mp4"
    create_plots: true
    plot_samples: 5
    plot_style: "seaborn"
    use_ensemble: false
    ensemble_size: 3
    compute_uncertainty: false
    num_mc_samples: 10

# GAN Model Configuration
gan_default:
  name: "gan_default"
  description: "Default configuration for GAN-based video generation"
  version: "1.0.0"
  created_at: "2024-01-01T00:00:00"
  
  system:
    environment: "development"
    debug: true
    log_level: "INFO"
    base_dir: "."
    config_dir: "configs"
    output_dir: "outputs"
    logs_dir: "logs"
    num_threads: 4
    memory_limit: null
    gpu_memory_fraction: 0.9
    enable_security: true
    max_file_size: 104857600
    allowed_file_types: [".mp4", ".avi", ".mov"]
  
  model:
    model_type: "gan"
    model_name: "gan_model"
    version: "1.0.0"
    input_channels: 3
    output_channels: 3
    latent_dim: 512
    hidden_dims: [64, 128, 256, 512]
    num_layers: 4
    dropout_rate: 0.1
    use_batch_norm: true
    activation: "relu"
    frame_size: [256, 256]
    num_frames: 16
    temporal_stride: 1
    fps: 30
    device: "cuda"
    dtype: "float16"
    use_mixed_precision: true
    use_gradient_checkpointing: false
    diffusion_steps: 1000
    noise_schedule: "linear"
    classifier_free_guidance: true
    guidance_scale: 7.5
  
  data:
    data_dir: "data/videos"
    metadata_file: null
    cache_dir: null
    frame_size: [256, 256]
    num_frames: 16
    fps: 30
    channels: 3
    batch_size: 8
    num_workers: 4
    pin_memory: true
    shuffle: true
    drop_last: true
    normalize: true
    normalize_mean: [0.485, 0.456, 0.406]
    normalize_std: [0.229, 0.224, 0.225]
    augment: true
    cache_data: false
    max_cache_size: 1000
    horizontal_flip_prob: 0.5
    vertical_flip_prob: 0.0
    rotation_prob: 0.2
    rotation_degrees: 15.0
    crop_prob: 0.3
    crop_ratio: 0.8
    brightness_jitter: 0.1
    contrast_jitter: 0.1
    saturation_jitter: 0.1
    hue_jitter: 0.05
    train_split: 0.8
    val_split: 0.1
    test_split: 0.1
    random_seed: 42
  
  training:
    num_epochs: 100
    batch_size: 8
    learning_rate: 0.0002
    weight_decay: 0.00001
    gradient_clip: 1.0
    max_grad_norm: 1.0
    optimizer: "adam"
    optimizer_params: {}
    scheduler: "cosine"
    scheduler_params: {}
    loss_type: "adversarial"
    loss_weights: {}
    save_frequency: 10
    eval_frequency: 5
    log_frequency: 100
    early_stopping_patience: 20
    early_stopping_min_delta: 0.0001
    checkpoint_dir: "checkpoints"
    save_best_only: true
    max_checkpoints: 5
    resume_from_checkpoint: null
    use_wandb: false
    use_tensorboard: true
    experiment_name: "ai_video_training"
    project_name: "ai_video"
    use_amp: true
    use_gradient_accumulation: false
    gradient_accumulation_steps: 1
    use_ddp: false
    local_rank: -1
  
  evaluation:
    batch_size: 8
    num_samples: null
    device: "cuda"
    compute_psnr: true
    compute_ssim: true
    compute_lpips: true
    compute_fid: true
    compute_inception_score: true
    save_results: true
    save_videos: false
    output_dir: "evaluation_results"
    save_format: "mp4"
    create_plots: true
    plot_samples: 5
    plot_style: "seaborn"
    use_ensemble: false
    ensemble_size: 3
    compute_uncertainty: false
    num_mc_samples: 10

# Transformer Model Configuration
transformer_default:
  name: "transformer_default"
  description: "Default configuration for transformer-based video generation"
  version: "1.0.0"
  created_at: "2024-01-01T00:00:00"
  
  system:
    environment: "development"
    debug: true
    log_level: "INFO"
    base_dir: "."
    config_dir: "configs"
    output_dir: "outputs"
    logs_dir: "logs"
    num_threads: 4
    memory_limit: null
    gpu_memory_fraction: 0.9
    enable_security: true
    max_file_size: 104857600
    allowed_file_types: [".mp4", ".avi", ".mov"]
  
  model:
    model_type: "transformer"
    model_name: "transformer_model"
    version: "1.0.0"
    input_channels: 3
    output_channels: 3
    latent_dim: 512
    hidden_dims: [64, 128, 256, 512]
    num_layers: 6
    dropout_rate: 0.1
    use_batch_norm: true
    activation: "gelu"
    frame_size: [256, 256]
    num_frames: 16
    temporal_stride: 1
    fps: 30
    device: "cuda"
    dtype: "float16"
    use_mixed_precision: true
    use_gradient_checkpointing: true
    diffusion_steps: 1000
    noise_schedule: "linear"
    classifier_free_guidance: true
    guidance_scale: 7.5
  
  data:
    data_dir: "data/videos"
    metadata_file: null
    cache_dir: null
    frame_size: [256, 256]
    num_frames: 16
    fps: 30
    channels: 3
    batch_size: 4
    num_workers: 4
    pin_memory: true
    shuffle: true
    drop_last: true
    normalize: true
    normalize_mean: [0.485, 0.456, 0.406]
    normalize_std: [0.229, 0.224, 0.225]
    augment: true
    cache_data: false
    max_cache_size: 1000
    horizontal_flip_prob: 0.5
    vertical_flip_prob: 0.0
    rotation_prob: 0.2
    rotation_degrees: 15.0
    crop_prob: 0.3
    crop_ratio: 0.8
    brightness_jitter: 0.1
    contrast_jitter: 0.1
    saturation_jitter: 0.1
    hue_jitter: 0.05
    train_split: 0.8
    val_split: 0.1
    test_split: 0.1
    random_seed: 42
  
  training:
    num_epochs: 100
    batch_size: 4
    learning_rate: 0.0001
    weight_decay: 0.00001
    gradient_clip: 1.0
    max_grad_norm: 1.0
    optimizer: "adamw"
    optimizer_params: {}
    scheduler: "cosine"
    scheduler_params: {}
    loss_type: "mse"
    loss_weights: {}
    save_frequency: 10
    eval_frequency: 5
    log_frequency: 100
    early_stopping_patience: 20
    early_stopping_min_delta: 0.0001
    checkpoint_dir: "checkpoints"
    save_best_only: true
    max_checkpoints: 5
    resume_from_checkpoint: null
    use_wandb: false
    use_tensorboard: true
    experiment_name: "ai_video_training"
    project_name: "ai_video"
    use_amp: true
    use_gradient_accumulation: true
    gradient_accumulation_steps: 2
    use_ddp: false
    local_rank: -1
  
  evaluation:
    batch_size: 4
    num_samples: null
    device: "cuda"
    compute_psnr: true
    compute_ssim: true
    compute_lpips: true
    compute_fid: false
    compute_inception_score: false
    save_results: true
    save_videos: false
    output_dir: "evaluation_results"
    save_format: "mp4"
    create_plots: true
    plot_samples: 5
    plot_style: "seaborn"
    use_ensemble: false
    ensemble_size: 3
    compute_uncertainty: false
    num_mc_samples: 10

# High-Resolution Configuration
high_res_config:
  name: "high_res_config"
  description: "Configuration for high-resolution video generation"
  version: "1.0.0"
  created_at: "2024-01-01T00:00:00"
  
  system:
    environment: "development"
    debug: true
    log_level: "INFO"
    base_dir: "."
    config_dir: "configs"
    output_dir: "outputs"
    logs_dir: "logs"
    num_threads: 8
    memory_limit: 16384
    gpu_memory_fraction: 0.95
    enable_security: true
    max_file_size: 104857600
    allowed_file_types: [".mp4", ".avi", ".mov"]
  
  model:
    model_type: "diffusion"
    model_name: "high_res_diffusion"
    version: "1.0.0"
    input_channels: 3
    output_channels: 3
    latent_dim: 1024
    hidden_dims: [128, 256, 512, 1024]
    num_layers: 6
    dropout_rate: 0.1
    use_batch_norm: true
    activation: "gelu"
    frame_size: [512, 512]
    num_frames: 24
    temporal_stride: 1
    fps: 30
    device: "cuda"
    dtype: "float16"
    use_mixed_precision: true
    use_gradient_checkpointing: true
    diffusion_steps: 1000
    noise_schedule: "cosine"
    classifier_free_guidance: true
    guidance_scale: 7.5
  
  data:
    data_dir: "data/high_res_videos"
    metadata_file: null
    cache_dir: "cache/high_res"
    frame_size: [512, 512]
    num_frames: 24
    fps: 30
    channels: 3
    batch_size: 2
    num_workers: 8
    pin_memory: true
    shuffle: true
    drop_last: true
    normalize: true
    normalize_mean: [0.485, 0.456, 0.406]
    normalize_std: [0.229, 0.224, 0.225]
    augment: true
    cache_data: true
    max_cache_size: 500
    horizontal_flip_prob: 0.5
    vertical_flip_prob: 0.0
    rotation_prob: 0.1
    rotation_degrees: 10.0
    crop_prob: 0.2
    crop_ratio: 0.9
    brightness_jitter: 0.05
    contrast_jitter: 0.05
    saturation_jitter: 0.05
    hue_jitter: 0.02
    train_split: 0.8
    val_split: 0.1
    test_split: 0.1
    random_seed: 42
  
  training:
    num_epochs: 200
    batch_size: 2
    learning_rate: 0.00005
    weight_decay: 0.00001
    gradient_clip: 1.0
    max_grad_norm: 1.0
    optimizer: "adamw"
    optimizer_params: {}
    scheduler: "cosine"
    scheduler_params: {}
    loss_type: "combined"
    loss_weights: {"mse": 1.0, "perceptual": 0.1}
    save_frequency: 20
    eval_frequency: 10
    log_frequency: 50
    early_stopping_patience: 30
    early_stopping_min_delta: 0.0001
    checkpoint_dir: "checkpoints/high_res"
    save_best_only: true
    max_checkpoints: 10
    resume_from_checkpoint: null
    use_wandb: true
    use_tensorboard: true
    experiment_name: "high_res_video_training"
    project_name: "ai_video"
    use_amp: true
    use_gradient_accumulation: true
    gradient_accumulation_steps: 4
    use_ddp: false
    local_rank: -1
  
  evaluation:
    batch_size: 1
    num_samples: null
    device: "cuda"
    compute_psnr: true
    compute_ssim: true
    compute_lpips: true
    compute_fid: true
    compute_inception_score: true
    save_results: true
    save_videos: true
    output_dir: "evaluation_results/high_res"
    save_format: "mp4"
    create_plots: true
    plot_samples: 3
    plot_style: "seaborn"
    use_ensemble: true
    ensemble_size: 5
    compute_uncertainty: true
    num_mc_samples: 20

# Fast Training Configuration
fast_training_config:
  name: "fast_training_config"
  description: "Configuration for fast training and experimentation"
  version: "1.0.0"
  created_at: "2024-01-01T00:00:00"
  
  system:
    environment: "development"
    debug: true
    log_level: "DEBUG"
    base_dir: "."
    config_dir: "configs"
    output_dir: "outputs"
    logs_dir: "logs"
    num_threads: 4
    memory_limit: null
    gpu_memory_fraction: 0.8
    enable_security: true
    max_file_size: 104857600
    allowed_file_types: [".mp4", ".avi", ".mov"]
  
  model:
    model_type: "diffusion"
    model_name: "fast_diffusion"
    version: "1.0.0"
    input_channels: 3
    output_channels: 3
    latent_dim: 256
    hidden_dims: [32, 64, 128, 256]
    num_layers: 3
    dropout_rate: 0.1
    use_batch_norm: true
    activation: "relu"
    frame_size: [128, 128]
    num_frames: 8
    temporal_stride: 1
    fps: 30
    device: "cuda"
    dtype: "float16"
    use_mixed_precision: true
    use_gradient_checkpointing: false
    diffusion_steps: 100
    noise_schedule: "linear"
    classifier_free_guidance: false
    guidance_scale: 1.0
  
  data:
    data_dir: "data/fast_videos"
    metadata_file: null
    cache_dir: null
    frame_size: [128, 128]
    num_frames: 8
    fps: 30
    channels: 3
    batch_size: 16
    num_workers: 4
    pin_memory: true
    shuffle: true
    drop_last: true
    normalize: true
    normalize_mean: [0.485, 0.456, 0.406]
    normalize_std: [0.229, 0.224, 0.225]
    augment: false
    cache_data: false
    max_cache_size: 100
    horizontal_flip_prob: 0.0
    vertical_flip_prob: 0.0
    rotation_prob: 0.0
    rotation_degrees: 0.0
    crop_prob: 0.0
    crop_ratio: 1.0
    brightness_jitter: 0.0
    contrast_jitter: 0.0
    saturation_jitter: 0.0
    hue_jitter: 0.0
    train_split: 0.8
    val_split: 0.1
    test_split: 0.1
    random_seed: 42
  
  training:
    num_epochs: 10
    batch_size: 16
    learning_rate: 0.001
    weight_decay: 0.00001
    gradient_clip: 1.0
    max_grad_norm: 1.0
    optimizer: "adam"
    optimizer_params: {}
    scheduler: "step"
    scheduler_params: {"step_size": 5, "gamma": 0.5}
    loss_type: "mse"
    loss_weights: {}
    save_frequency: 2
    eval_frequency: 1
    log_frequency: 10
    early_stopping_patience: 5
    early_stopping_min_delta: 0.001
    checkpoint_dir: "checkpoints/fast"
    save_best_only: false
    max_checkpoints: 3
    resume_from_checkpoint: null
    use_wandb: false
    use_tensorboard: true
    experiment_name: "fast_video_training"
    project_name: "ai_video"
    use_amp: true
    use_gradient_accumulation: false
    gradient_accumulation_steps: 1
    use_ddp: false
    local_rank: -1
  
  evaluation:
    batch_size: 16
    num_samples: 100
    device: "cuda"
    compute_psnr: true
    compute_ssim: true
    compute_lpips: false
    compute_fid: false
    compute_inception_score: false
    save_results: true
    save_videos: false
    output_dir: "evaluation_results/fast"
    save_format: "mp4"
    create_plots: true
    plot_samples: 3
    plot_style: "default"
    use_ensemble: false
    ensemble_size: 1
    compute_uncertainty: false
    num_mc_samples: 1 