"""
Core Interfaces

Protocols and interfaces for dependency inversion and loose coupling.
Following SOLID principles, especially Dependency Inversion Principle.
"""

from typing import Protocol, Optional, List, Dict, Any
from abc import ABC, abstractmethod


class IChatRepository(Protocol):
    """Protocol for chat repository operations."""
    
    def get_by_id(self, chat_id: str) -> Optional[Any]: ...
    def create(self, **kwargs) -> Any: ...
    def update(self, chat_id: str, **kwargs) -> Optional[Any]: ...
    def delete(self, chat_id: str) -> bool: ...
    def get_public_chats(self, skip: int, limit: int, sort_by: str, order: str) -> List[Any]: ...
    def get_featured_chats(self, limit: int) -> List[Any]: ...
    def search_by_query(self, query: str, skip: int, limit: int) -> List[Any]: ...
    def count_search_results(self, **kwargs) -> int: ...
    def increment_view_count_and_score(self, chat_id: str, score: float) -> bool: ...
    def increment_vote_count_and_score(self, chat_id: str, increment: int, score: float) -> bool: ...
    def increment_remix_count_and_score(self, chat_id: str, score: float) -> bool: ...
    def get_rank_by_score(self, score: float) -> int: ...


class IVoteRepository(Protocol):
    """Protocol for vote repository operations."""
    
    def get_user_vote(self, chat_id: str, user_id: str) -> Optional[Any]: ...
    def get_user_votes_batch(self, chat_ids: List[str], user_id: str) -> Dict[str, Any]: ...
    def create(self, **kwargs) -> Any: ...
    def update(self, vote_id: str, **kwargs) -> Optional[Any]: ...
    def delete_by_chat_id(self, chat_id: str) -> int: ...


class IViewRepository(Protocol):
    """Protocol for view repository operations."""
    
    def create(self, **kwargs) -> Any: ...
    def delete_by_chat_id(self, chat_id: str) -> int: ...


class IRemixRepository(Protocol):
    """Protocol for remix repository operations."""
    
    def create(self, **kwargs) -> Any: ...
    def get_by_original_chat_id(self, original_chat_id: str) -> List[Any]: ...
    def delete_by_original_chat_id(self, original_chat_id: str) -> int: ...


class IRankingService(Protocol):
    """Protocol for ranking service operations."""
    
    def calculate_score(
        self,
        vote_count: int,
        remix_count: int,
        view_count: int,
        created_at: Any
    ) -> float: ...


class IValidator(Protocol):
    """Protocol for validation operations."""
    
    def validate_chat_id(self, chat_id: str) -> str: ...
    def validate_user_id(self, user_id: str) -> str: ...
    def validate_title(self, title: str) -> str: ...
    def validate_chat_content(self, chat_content: str) -> str: ...
    def process_tags(self, tags: Optional[List[str]]) -> Optional[str]: ...
    def ensure_ownership(self, chat: Any, user_id: str) -> None: ...


class IAIProcessor(Protocol):
    """Protocol for AI processing operations."""
    
    def process_chat(self, chat: Any) -> None: ...


class IScoreManager(Protocol):
    """Protocol for score management operations."""
    
    def calculate_score(
        self,
        chat: Any,
        vote_count: Optional[int] = None,
        remix_count: Optional[int] = None,
        view_count: Optional[int] = None
    ) -> float: ...


class IIdentityService(Protocol):
    """Protocol for identity and authentication operations."""
    
    def get_user_id(self, request: Any) -> str: ...
    def get_optional_user_id(self, request: Any) -> Optional[str]: ...
    def validate_user_id(self, user_id: str) -> str: ...
    def is_authenticated(self, request: Any) -> bool: ...






