"""
Constants
=========

Application-wide constants for Character Clothing Changer AI.
"""

# Default values
DEFAULT_MAX_PARALLEL_TASKS = 5
DEFAULT_OUTPUT_DIR = "clothing_changer_output"
DEFAULT_CACHE_TTL_HOURS = 24
DEFAULT_MAX_RETRIES = 3
DEFAULT_RATE_LIMIT_RPS = 10.0
DEFAULT_RATE_LIMIT_BURST = 20

# Directory names
DIR_RESULTS = "results"
DIR_TASKS = "tasks"
DIR_STORAGE = "storage"
DIR_UPLOADS = "uploads"
DIR_CACHE = "cache"
DIR_LOGS = "logs"

# Output directories list
OUTPUT_DIRECTORIES = [
    DIR_RESULTS,
    DIR_TASKS,
    DIR_STORAGE,
    DIR_UPLOADS,
    DIR_CACHE,
    DIR_LOGS
]

# File size limits (MB)
DEFAULT_MAX_IMAGE_SIZE_MB = 50
DEFAULT_MAX_FILE_SIZE_MB = 500

# Supported formats
SUPPORTED_IMAGE_FORMATS = [".jpg", ".jpeg", ".png", ".webp", ".bmp", ".gif"]

# Task priorities
PRIORITY_LOW = 0
PRIORITY_NORMAL = 5
PRIORITY_HIGH = 10
PRIORITY_CRITICAL = 15

# Retry strategies
RETRY_STRATEGY_IMMEDIATE = "immediate"
RETRY_STRATEGY_EXPONENTIAL_BACKOFF = "exponential_backoff"
RETRY_STRATEGY_FIXED_DELAY = "fixed_delay"
RETRY_STRATEGY_LINEAR_BACKOFF = "linear_backoff"

# Logging
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_MAX_BYTES = 10 * 1024 * 1024  # 10MB
DEFAULT_LOG_BACKUP_COUNT = 5

# Metrics
METRICS_MAX_POINTS = 10000
METRICS_HISTORY_LIMIT = 1000

# Events
EVENT_HISTORY_LIMIT = 1000

# Backup
DEFAULT_BACKUP_DIR = "backups"

# Cache
DEFAULT_CACHE_SIZE = 1000
DEFAULT_CACHE_TTL_SECONDS = 3600

# Queue
DEFAULT_QUEUE_MAX_SIZE = 10000
DEFAULT_QUEUE_TIMEOUT_SECONDS = 300

# Batch operations
DEFAULT_BATCH_SIZE = 100
DEFAULT_MAX_CONCURRENT_BATCHES = 5

# Health check
DEFAULT_HEALTH_CHECK_INTERVAL_SECONDS = 30
DEFAULT_HEALTH_CHECK_TIMEOUT_SECONDS = 5

# Rate limiting
DEFAULT_RATE_LIMIT_WINDOW_SECONDS = 60

# Circuit breaker
DEFAULT_CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5
DEFAULT_CIRCUIT_BREAKER_SUCCESS_THRESHOLD = 2
DEFAULT_CIRCUIT_BREAKER_TIMEOUT_SECONDS = 60

# Security
DEFAULT_TOKEN_LENGTH = 32
DEFAULT_PASSWORD_HASH_ITERATIONS = 100000

# Observability
DEFAULT_OBSERVABILITY_MAX_ENTRIES = 10000

# Storage
DEFAULT_STORAGE_MAX_ITEMS = 100000
