version: '3.8'

services:
  # Main API
  api:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./export_ia.db
    volumes:
      - ./exports:/app/exports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database (optional, for production)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=export_ia
      - POSTGRES_USER=export_ia
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data:




