global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'frontier-model-run'
    environment: 'production'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "alerts.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Inference API
  - job_name: 'inference-api'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['inference-api:8080']
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node exporter (if deployed)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # Redis exporter (optional)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']


