"""
Data models for Social Video Transcriber AI
"""

from typing import List, Optional, Dict, Any
from enum import Enum
from datetime import datetime
from pydantic import BaseModel, Field, validator, HttpUrl
from uuid import UUID, uuid4
import re


class SupportedPlatform(str, Enum):
    """Supported video platforms"""
    TIKTOK = "tiktok"
    INSTAGRAM = "instagram"
    YOUTUBE = "youtube"
    AUTO = "auto"  # Auto-detect platform


class TranscriptionStatus(str, Enum):
    """Status of transcription job"""
    PENDING = "pending"
    DOWNLOADING = "downloading"
    EXTRACTING_AUDIO = "extracting_audio"
    TRANSCRIBING = "transcribing"
    ANALYZING = "analyzing"
    COMPLETED = "completed"
    FAILED = "failed"


class ContentFramework(str, Enum):
    """Content framework types detected by AI"""
    HOOK_STORY_OFFER = "hook_story_offer"
    PROBLEM_AGITATE_SOLVE = "problem_agitate_solve"
    AIDA = "aida"  # Attention, Interest, Desire, Action
    STAR = "star"  # Situation, Task, Action, Result
    BAB = "bab"  # Before, After, Bridge
    EDUCATIONAL = "educational"
    STORYTELLING = "storytelling"
    LISTICLE = "listicle"
    TUTORIAL = "tutorial"
    REVIEW = "review"
    NEWS = "news"
    ENTERTAINMENT = "entertainment"
    MOTIVATIONAL = "motivational"
    CUSTOM = "custom"


class TranscriptionSegment(BaseModel):
    """A segment of transcription with timing"""
    id: int
    start_time: float  # Seconds
    end_time: float  # Seconds
    text: str
    confidence: Optional[float] = None
    speaker: Optional[str] = None  # For speaker diarization
    
    @property
    def duration(self) -> float:
        return self.end_time - self.start_time
    
    @property
    def formatted_timestamp(self) -> str:
        """Format timestamp as [MM:SS -> MM:SS]"""
        start = f"{int(self.start_time // 60):02d}:{int(self.start_time % 60):02d}"
        end = f"{int(self.end_time // 60):02d}:{int(self.end_time % 60):02d}"
        return f"[{start} -> {end}]"
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "text": self.text,
            "confidence": self.confidence,
            "speaker": self.speaker,
            "formatted_timestamp": self.formatted_timestamp,
        }


class ContentAnalysis(BaseModel):
    """AI analysis of content structure and framework"""
    framework: ContentFramework
    framework_confidence: float = Field(ge=0.0, le=1.0)
    structure: Dict[str, Any] = Field(default_factory=dict)
    """
    Structure breakdown, e.g.:
    {
        "hook": {"text": "...", "start": 0, "end": 5},
        "story": {"text": "...", "start": 5, "end": 45},
        "offer": {"text": "...", "start": 45, "end": 60}
    }
    """
    key_points: List[str] = Field(default_factory=list)
    tone: str = "neutral"  # casual, professional, humorous, serious, etc.
    target_audience: Optional[str] = None
    call_to_action: Optional[str] = None
    hashtags_suggested: List[str] = Field(default_factory=list)
    content_type: str = "general"
    language_detected: str = "es"
    word_count: int = 0
    estimated_reading_time: float = 0.0  # Minutes
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "framework": self.framework.value,
            "framework_confidence": self.framework_confidence,
            "structure": self.structure,
            "key_points": self.key_points,
            "tone": self.tone,
            "target_audience": self.target_audience,
            "call_to_action": self.call_to_action,
            "hashtags_suggested": self.hashtags_suggested,
            "content_type": self.content_type,
            "language_detected": self.language_detected,
            "word_count": self.word_count,
            "estimated_reading_time": self.estimated_reading_time,
        }


class TextVariant(BaseModel):
    """A text variant generated by AI"""
    id: UUID = Field(default_factory=uuid4)
    original_text: str
    variant_text: str
    variant_type: str = "rewrite"  # rewrite, expand, condense, tone_change
    similarity_score: float = Field(ge=0.0, le=1.0)  # How similar to original
    preserves_structure: bool = True
    preserves_length: bool = True
    tone: Optional[str] = None
    word_count: int = 0
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": str(self.id),
            "original_text": self.original_text,
            "variant_text": self.variant_text,
            "variant_type": self.variant_type,
            "similarity_score": self.similarity_score,
            "preserves_structure": self.preserves_structure,
            "preserves_length": self.preserves_length,
            "tone": self.tone,
            "word_count": self.word_count,
            "created_at": self.created_at.isoformat(),
        }


class TranscriptionRequest(BaseModel):
    """Request model for video transcription"""
    video_url: str = Field(..., description="URL of the video (TikTok, Instagram, or YouTube)")
    platform: SupportedPlatform = SupportedPlatform.AUTO
    include_timestamps: bool = True
    include_analysis: bool = True
    language: Optional[str] = None  # ISO 639-1 code, None for auto-detect
    webhook_url: Optional[str] = None  # Callback URL for async processing
    
    @validator("video_url")
    def validate_video_url(cls, v):
        # Basic URL validation
        url_pattern = re.compile(
            r'^https?://'
            r'(?:(?:www\.)?(?:youtube\.com|youtu\.be)|'
            r'(?:www\.)?(?:tiktok\.com|vm\.tiktok\.com)|'
            r'(?:www\.)?instagram\.com)'
            r'/.*$',
            re.IGNORECASE
        )
        if not url_pattern.match(v):
            raise ValueError("URL must be from YouTube, TikTok, or Instagram")
        return v
    
    class Config:
        json_schema_extra = {
            "example": {
                "video_url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                "platform": "auto",
                "include_timestamps": True,
                "include_analysis": True,
                "language": "es",
            }
        }


class TranscriptionResponse(BaseModel):
    """Response model for transcription"""
    job_id: UUID = Field(default_factory=uuid4)
    status: TranscriptionStatus = TranscriptionStatus.PENDING
    platform_detected: Optional[SupportedPlatform] = None
    video_title: Optional[str] = None
    video_duration: Optional[float] = None  # Seconds
    video_author: Optional[str] = None
    
    # Transcription results
    full_text: Optional[str] = None
    full_text_with_timestamps: Optional[str] = None
    segments: List[TranscriptionSegment] = Field(default_factory=list)
    
    # AI Analysis
    analysis: Optional[ContentAnalysis] = None
    
    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None
    processing_time: Optional[float] = None  # Seconds
    error: Optional[str] = None
    
    class Config:
        json_schema_extra = {
            "example": {
                "job_id": "123e4567-e89b-12d3-a456-426614174000",
                "status": "completed",
                "platform_detected": "youtube",
                "video_title": "Example Video",
                "video_duration": 120.5,
                "full_text": "This is the transcribed text...",
                "full_text_with_timestamps": "[00:00 -> 00:05] This is the transcribed text...",
            }
        }


class VariantRequest(BaseModel):
    """Request model for generating text variants"""
    text: Optional[str] = None  # If None, use transcription from job_id
    job_id: Optional[UUID] = None  # Use transcription from previous job
    num_variants: int = Field(default=3, ge=1, le=10)
    preserve_structure: bool = True
    preserve_length: bool = True
    target_tone: Optional[str] = None  # casual, professional, humorous, etc.
    custom_instructions: Optional[str] = None
    
    @validator("text", always=True)
    def validate_text_or_job_id(cls, v, values):
        if v is None and values.get("job_id") is None:
            raise ValueError("Either 'text' or 'job_id' must be provided")
        return v
    
    class Config:
        json_schema_extra = {
            "example": {
                "text": "Original text to create variants from...",
                "num_variants": 3,
                "preserve_structure": True,
                "preserve_length": True,
                "target_tone": "professional",
            }
        }


class VariantResponse(BaseModel):
    """Response model for variant generation"""
    request_id: UUID = Field(default_factory=uuid4)
    original_text: str
    variants: List[TextVariant] = Field(default_factory=list)
    analysis: Optional[ContentAnalysis] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    processing_time: Optional[float] = None
    
    class Config:
        json_schema_extra = {
            "example": {
                "request_id": "123e4567-e89b-12d3-a456-426614174000",
                "original_text": "Original text...",
                "variants": [
                    {
                        "variant_text": "First variant...",
                        "similarity_score": 0.85,
                    }
                ],
            }
        }


class AnalysisRequest(BaseModel):
    """Request model for standalone text analysis"""
    text: str = Field(..., min_length=10)
    analyze_framework: bool = True
    analyze_structure: bool = True
    suggest_improvements: bool = False
    
    class Config:
        json_schema_extra = {
            "example": {
                "text": "Text to analyze for framework and structure...",
                "analyze_framework": True,
                "analyze_structure": True,
                "suggest_improvements": True,
            }
        }


class AnalysisResponse(BaseModel):
    """Response model for text analysis"""
    request_id: UUID = Field(default_factory=uuid4)
    analysis: ContentAnalysis
    improvements: Optional[List[str]] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        json_schema_extra = {
            "example": {
                "request_id": "123e4567-e89b-12d3-a456-426614174000",
                "analysis": {
                    "framework": "hook_story_offer",
                    "framework_confidence": 0.92,
                    "structure": {},
                },
            }
        }


class QuickVariantRequest(BaseModel):
    """Request for quick one-click variant generation"""
    job_id: UUID = Field(..., description="Job ID from a previous transcription")
    
    class Config:
        json_schema_extra = {
            "example": {
                "job_id": "123e4567-e89b-12d3-a456-426614174000",
            }
        }












