/**
 * Hooks Module - Exports all custom React hooks
 */

export { useModelCreation } from './useModelCreation'
export { useModelWatcher } from './useModelWatcher'
export { useDebounce } from './useDebounce'
export { useLocalStorage } from './useLocalStorage'
export { useLocalStorageSync } from './useLocalStorageSync'
export { useCopyToClipboard } from './useCopyToClipboard'
export { useClipboard } from './useClipboard'
export { useKeyboardShortcuts } from './useKeyboardShortcuts'
export { useTruthGPTAPI, type UseTruthGPTAPIResult } from './useTruthGPTAPI'
export { useEnhancedChat } from './useEnhancedChat'
export { useKeyboard } from './useKeyboard'
export { useAnalytics } from './useAnalytics'
export { usePerformance } from './usePerformance'
export { useLogger } from './useLogger'
export { useCounter } from './useCounter'
export { useToggle } from './useToggle'
export { useTimeout } from './useTimeout'
export { useInterval } from './useInterval'
export { usePrevious } from './usePrevious'
export { useMemoizedCallback } from './useMemoizedCallback'
export { useCache } from './useCache'
export { useId } from './useId'
export { useEventListener } from './useEventListener'
export { useClickOutside } from './useClickOutside'
export { useMediaQuery } from './useMediaQuery'
export { useWindowSize } from './useWindowSize'
export { useDevice } from './useDevice'
export { useOnline } from './useOnline'
export { useScroll } from './useScroll'
export { useLazyLoad } from './useLazyLoad'
export { useVirtualList } from './useVirtualList'
export { useAnimation } from './useAnimation'
export { useDragAndDrop } from './useDragAndDrop'
export { useForm } from './useForm'
export { useSchema } from './useSchema'
export { useModal } from './useModal'
export { useToast } from './useToast'
export { useConfirm } from './useConfirm'
export { useErrorHandler } from './useErrorHandler'
export { useAsync } from './useAsync'
export { useRouter } from './useRouter'
export { useReducerWithActions } from './useReducerWithActions'
export { useStateMachine } from './useStateMachine'
export { useEventEmitter } from './useEventEmitter'
export { useIntersectionObserver } from './useIntersectionObserver'
export { usePersistentState } from './usePersistentState'
export { useSharedState } from './useSharedState'
export { useI18n } from './useI18n'
export { useBulkChat, type UseBulkChatOptions, type UseBulkChatReturn, type BulkChatMessage, type BulkChatSession } from './useBulkChat'
export { useModelCreator, type UseModelCreatorResult, type ModelCreationOptions, type ModelCreationResult } from './useModelCreator'
export { useModelTemplates, type UseModelTemplatesResult, type ModelTemplate } from './useModelTemplates'
export { useModelHistory, type UseModelHistoryResult, type UseModelHistoryOptions, type ModelHistoryItem } from './useModelHistory'
export { useModelValidator, type ValidationResult, type ModelSpec } from './useModelValidator'
export { useModelStatusPoller, type UseModelStatusPollerResult, type PollingOptions, type ModelStatus } from './useModelStatusPoller'
export { useModelOperations, type UseModelOperationsResult, type ModelOperationCallbacks } from './useModelOperations'
export { useModelAnalytics, type UseModelAnalyticsResult, type ModelAnalytics } from './useModelAnalytics'
export { useModelCache, type UseModelCacheResult, type UseModelCacheOptions, type CachedModel } from './useModelCache'
export { useModelPerformance, type UseModelPerformanceResult, type ModelPerformanceMetrics } from './useModelPerformance'
export { useOptimizedModelCreation, type OptimizedModelCreationOptions, type OptimizedModelCreationResult } from './useOptimizedModelCreation'
export { useSmartModelCreation, type UseSmartModelCreationResult, type SmartModelCreationOptions } from './useSmartModelCreation'
export { useDebouncedModelCreation, type UseDebouncedModelCreationResult, type UseDebouncedModelCreationOptions } from './useDebouncedModelCreation'
export { useModelRetry, type RetryStrategy, type RetryOptions, type RetryResult } from './useModelRetry'
export { useModelQueue, type UseModelQueueResult, type UseModelQueueOptions, type QueuedModel } from './useModelQueue'
export { useModelNotifications, type ModelNotificationOptions } from './useModelNotifications'
export { useIntegratedModelCreation, type UseIntegratedModelCreationResult, type IntegratedModelCreationOptions } from './useIntegratedModelCreation'
export { useModelComparison, type UseModelComparisonResult, type ModelComparison, type ModelMetrics } from './useModelComparison'
export { useModelOptimizer, type UseModelOptimizerResult, type ModelOptimizationSuggestions } from './useModelOptimizer'
export { useModelShortcuts, type UseModelShortcutsResult, type UseModelShortcutsOptions, type ModelShortcut } from './useModelShortcuts'
export { useModelTesting, type UseModelTestingResult, type TestResult, type ModelTest } from './useModelTesting'
export { useCompleteModelSystem, type UseCompleteModelSystemResult, type CompleteModelSystemOptions, type CreateModelWithSystemOptions } from './useCompleteModelSystem'
export { useTypedModelSystem, type UseTypedModelSystemResult, type UseTypedModelSystemOptions } from './useTypedModelSystem'
export { useModelPerformanceOptimizer, type UseModelPerformanceOptimizerResult, type PerformanceConfig } from './useModelPerformanceOptimizer'
export { useModelAccessibility, type UseModelAccessibilityResult, type AccessibilityOptions } from './useModelAccessibility'
export { useModelDevTools, type UseModelDevToolsResult, type DevToolsState } from './useModelDevTools'


