"""
Multiverse Core Module - Módulo Core de Multiverso
================================================

Módulo core de multiverso que contiene la lógica de dominio, aplicación e infraestructura
del sistema ultra-ultra-ultra-ultra-ultra-refactorizado con capacidades de multiverso.
"""

from .multiverse_domain.multiverse_aggregates import (
    MultiverseAggregate,
    UniverseClusterAggregate,
    RealityBubbleAggregate,
    ConsciousnessMatrixAggregate,
    TranscendenceFieldAggregate,
    OmniversalNetworkAggregate,
    HyperdimensionalRealityAggregate,
    TemporalConsciousnessAggregate,
    UniversalFabricAggregate,
    AbsoluteTranscendenceAggregate
)
from .multiverse_domain.multiverse_events import (
    MultiverseCreationEvent,
    UniverseClusterEvent,
    RealityBubbleEvent,
    ConsciousnessMatrixEvent,
    TranscendenceFieldEvent,
    OmniversalNetworkEvent,
    HyperdimensionalRealityEvent,
    TemporalConsciousnessEvent,
    UniversalFabricEvent,
    AbsoluteTranscendenceEvent,
    MultiverseEvolutionEvent,
    RealityFabricationEvent,
    ConsciousnessEvolutionEvent,
    TemporalManipulationEvent,
    OmniversalCommunicationEvent
)
from .multiverse_domain.multiverse_value_objects import (
    MultiverseId,
    UniverseClusterId,
    RealityBubbleId,
    ConsciousnessMatrixId,
    TranscendenceFieldId,
    OmniversalNetworkId,
    HyperdimensionalRealityId,
    TemporalConsciousnessId,
    UniversalFabricId,
    AbsoluteTranscendenceId,
    MultiverseCoordinate,
    UniverseClusterCoordinate,
    RealityBubbleCoordinate,
    ConsciousnessMatrixCoordinate,
    TranscendenceFieldCoordinate,
    OmniversalNetworkCoordinate,
    HyperdimensionalRealityCoordinate,
    TemporalConsciousnessCoordinate,
    UniversalFabricCoordinate,
    AbsoluteTranscendenceCoordinate
)
from .multiverse_application.multiverse_commands import (
    MultiverseCreationCommand,
    UniverseClusterCommand,
    RealityBubbleCommand,
    ConsciousnessMatrixCommand,
    TranscendenceFieldCommand,
    OmniversalNetworkCommand,
    HyperdimensionalRealityCommand,
    TemporalConsciousnessCommand,
    UniversalFabricCommand,
    AbsoluteTranscendenceCommand,
    MultiverseEvolutionCommand,
    RealityFabricationCommand,
    ConsciousnessEvolutionCommand,
    TemporalManipulationCommand,
    OmniversalCommunicationCommand
)
from .multiverse_application.multiverse_queries import (
    MultiverseSearchQuery,
    UniverseClusterQuery,
    RealityBubbleQuery,
    ConsciousnessMatrixQuery,
    TranscendenceFieldQuery,
    OmniversalNetworkQuery,
    HyperdimensionalRealityQuery,
    TemporalConsciousnessQuery,
    UniversalFabricQuery,
    AbsoluteTranscendenceQuery,
    MultiverseEvolutionQuery,
    RealityFabricationQuery,
    ConsciousnessEvolutionQuery,
    TemporalManipulationQuery,
    OmniversalCommunicationQuery
)
from .multiverse_infrastructure.multiverse_event_store import MultiverseEventStore
from .multiverse_infrastructure.multiverse_message_bus import MultiverseMessageBus
from .multiverse_infrastructure.multiverse_plugin_registry import MultiversePluginRegistry

__all__ = [
    "MultiverseAggregate",
    "UniverseClusterAggregate",
    "RealityBubbleAggregate",
    "ConsciousnessMatrixAggregate",
    "TranscendenceFieldAggregate",
    "OmniversalNetworkAggregate",
    "HyperdimensionalRealityAggregate",
    "TemporalConsciousnessAggregate",
    "UniversalFabricAggregate",
    "AbsoluteTranscendenceAggregate",
    "MultiverseCreationEvent",
    "UniverseClusterEvent",
    "RealityBubbleEvent",
    "ConsciousnessMatrixEvent",
    "TranscendenceFieldEvent",
    "OmniversalNetworkEvent",
    "HyperdimensionalRealityEvent",
    "TemporalConsciousnessEvent",
    "UniversalFabricEvent",
    "AbsoluteTranscendenceEvent",
    "MultiverseEvolutionEvent",
    "RealityFabricationEvent",
    "ConsciousnessEvolutionEvent",
    "TemporalManipulationEvent",
    "OmniversalCommunicationEvent",
    "MultiverseId",
    "UniverseClusterId",
    "RealityBubbleId",
    "ConsciousnessMatrixId",
    "TranscendenceFieldId",
    "OmniversalNetworkId",
    "HyperdimensionalRealityId",
    "TemporalConsciousnessId",
    "UniversalFabricId",
    "AbsoluteTranscendenceId",
    "MultiverseCoordinate",
    "UniverseClusterCoordinate",
    "RealityBubbleCoordinate",
    "ConsciousnessMatrixCoordinate",
    "TranscendenceFieldCoordinate",
    "OmniversalNetworkCoordinate",
    "HyperdimensionalRealityCoordinate",
    "TemporalConsciousnessCoordinate",
    "UniversalFabricCoordinate",
    "AbsoluteTranscendenceCoordinate",
    "MultiverseCreationCommand",
    "UniverseClusterCommand",
    "RealityBubbleCommand",
    "ConsciousnessMatrixCommand",
    "TranscendenceFieldCommand",
    "OmniversalNetworkCommand",
    "HyperdimensionalRealityCommand",
    "TemporalConsciousnessCommand",
    "UniversalFabricCommand",
    "AbsoluteTranscendenceCommand",
    "MultiverseEvolutionCommand",
    "RealityFabricationCommand",
    "ConsciousnessEvolutionCommand",
    "TemporalManipulationCommand",
    "OmniversalCommunicationCommand",
    "MultiverseSearchQuery",
    "UniverseClusterQuery",
    "RealityBubbleQuery",
    "ConsciousnessMatrixQuery",
    "TranscendenceFieldQuery",
    "OmniversalNetworkQuery",
    "HyperdimensionalRealityQuery",
    "TemporalConsciousnessQuery",
    "UniversalFabricQuery",
    "AbsoluteTranscendenceQuery",
    "MultiverseEvolutionQuery",
    "RealityFabricationQuery",
    "ConsciousnessEvolutionQuery",
    "TemporalManipulationQuery",
    "OmniversalCommunicationQuery",
    "MultiverseEventStore",
    "MultiverseMessageBus",
    "MultiversePluginRegistry"
]




