"""
Constants

Application-wide constants.
"""

# Quality Score Thresholds
QUALITY_EXCELLENT = 90.0
QUALITY_GOOD = 75.0
QUALITY_ACCEPTABLE = 60.0
QUALITY_POOR = 40.0
QUALITY_REJECTED = 0.0

# Defect Penalties
PENALTY_CRITICAL_DEFECT = 20.0
PENALTY_SEVERE_DEFECT = 15.0
PENALTY_MODERATE_DEFECT = 8.0
PENALTY_MINOR_DEFECT = 3.0

# Anomaly Penalties
PENALTY_HIGH_ANOMALY = 10.0
PENALTY_MEDIUM_ANOMALY = 5.0
PENALTY_LOW_ANOMALY = 2.0

# Image Constraints
MIN_IMAGE_WIDTH = 32
MIN_IMAGE_HEIGHT = 32
MAX_IMAGE_WIDTH = 10000
MAX_IMAGE_HEIGHT = 10000
SUPPORTED_IMAGE_CHANNELS = [1, 3, 4]

# Supported Image Formats
SUPPORTED_IMAGE_FORMATS = ["numpy", "bytes", "file_path", "base64"]

# Default Values
DEFAULT_IMAGE_SIZE = (224, 224)
DEFAULT_CONFIDENCE_THRESHOLD = 0.5
DEFAULT_ANOMALY_THRESHOLD = 0.7
DEFAULT_BATCH_SIZE = 8
DEFAULT_TIMEOUT = 30.0

# Cache Settings
DEFAULT_CACHE_SIZE = 1000
DEFAULT_CACHE_TTL = 3600  # 1 hour

# API Limits
MAX_FILE_SIZE = 10 * 1024 * 1024  # 10MB
MAX_BATCH_SIZE = 100

# Model Types
MODEL_TYPE_AUTOENCODER = "autoencoder"
MODEL_TYPE_CLASSIFIER = "classifier"
MODEL_TYPE_DIFFUSION = "diffusion"

# Detection Model Types
DETECTION_MODEL_YOLOV8 = "yolov8"
DETECTION_MODEL_FASTER_RCNN = "faster_rcnn"
DETECTION_MODEL_SSD = "ssd"



