"""
API constants
"""

from .api_constants import (
    DEFAULT_SEARCH_LIMIT,
    MAX_SEARCH_LIMIT,
    DEFAULT_RECOMMENDATION_LIMIT,
    MAX_RECOMMENDATION_LIMIT,
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    MIN_TRACKS_FOR_COMPARISON,
    MAX_TRACKS_FOR_COMPARISON,
    MAX_TRACKS_FOR_PLAYLIST_ANALYSIS,
    MIN_ARTISTS_FOR_COMPARISON,
    MAX_ARTISTS_FOR_COMPARISON,
    MAX_ARTISTS_FOR_NETWORK,
    DEFAULT_CACHE_TTL,
    SPOTIFY_CACHE_TTL,
    ANALYSIS_CACHE_TTL,
    DEFAULT_TIMEOUT,
    SPOTIFY_TIMEOUT,
    ANALYSIS_TIMEOUT,
    DEFAULT_MAX_RETRIES,
    DEFAULT_RETRY_DELAY,
    DEFAULT_BATCH_SIZE,
    DEFAULT_MAX_CONCURRENT,
    CURRENT_API_VERSION,
    SUPPORTED_VERSIONS
)

__all__ = [
    "DEFAULT_SEARCH_LIMIT",
    "MAX_SEARCH_LIMIT",
    "DEFAULT_RECOMMENDATION_LIMIT",
    "MAX_RECOMMENDATION_LIMIT",
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "MIN_TRACKS_FOR_COMPARISON",
    "MAX_TRACKS_FOR_COMPARISON",
    "MAX_TRACKS_FOR_PLAYLIST_ANALYSIS",
    "MIN_ARTISTS_FOR_COMPARISON",
    "MAX_ARTISTS_FOR_COMPARISON",
    "MAX_ARTISTS_FOR_NETWORK",
    "DEFAULT_CACHE_TTL",
    "SPOTIFY_CACHE_TTL",
    "ANALYSIS_CACHE_TTL",
    "DEFAULT_TIMEOUT",
    "SPOTIFY_TIMEOUT",
    "ANALYSIS_TIMEOUT",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_RETRY_DELAY",
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_MAX_CONCURRENT",
    "CURRENT_API_VERSION",
    "SUPPORTED_VERSIONS"
]

