"""
API constants
"""

# Default limits
DEFAULT_SEARCH_LIMIT = 10
MAX_SEARCH_LIMIT = 50
DEFAULT_RECOMMENDATION_LIMIT = 10
MAX_RECOMMENDATION_LIMIT = 100
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# Track limits
MIN_TRACKS_FOR_COMPARISON = 2
MAX_TRACKS_FOR_COMPARISON = 10
MAX_TRACKS_FOR_PLAYLIST_ANALYSIS = 100

# Artist limits
MIN_ARTISTS_FOR_COMPARISON = 2
MAX_ARTISTS_FOR_COMPARISON = 5
MAX_ARTISTS_FOR_NETWORK = 10

# Cache TTL (seconds)
DEFAULT_CACHE_TTL = 300
SPOTIFY_CACHE_TTL = 3600
ANALYSIS_CACHE_TTL = 1800

# Timeout values (seconds)
DEFAULT_TIMEOUT = 10
SPOTIFY_TIMEOUT = 15
ANALYSIS_TIMEOUT = 30

# Retry settings
DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_DELAY = 1.0

# Batch processing
DEFAULT_BATCH_SIZE = 10
DEFAULT_MAX_CONCURRENT = 5

# API versions
CURRENT_API_VERSION = "v2"
SUPPORTED_VERSIONS = ["v1", "v2"]

