"""
Playwright CI/CD Tests
======================
Tests optimized for CI/CD pipelines.
"""

import pytest
from playwright.sync_api import Page, Response
import time
import os


@pytest.fixture
def api_base_url():
    """API base URL from environment or default."""
    return os.getenv("API_BASE_URL", "http://localhost:8000")


@pytest.fixture
def ci_timeout():
    """Timeout for CI environments."""
    return int(os.getenv("CI_TIMEOUT", "30000"))


class TestPlaywrightCIFast:
    """Fast tests for CI."""
    
    @pytest.mark.playwright
    @pytest.mark.ci
    @pytest.mark.fast
    def test_health_check_ci(self, page, api_base_url, ci_timeout):
        """Fast health check for CI."""
        response = page.request.get(f"{api_base_url}/health", timeout=ci_timeout)
        assert response.status == 200
    
    @pytest.mark.playwright
    @pytest.mark.ci
    @pytest.mark.fast
    def test_api_accessible_ci(self, page, api_base_url, ci_timeout):
        """Fast API accessibility check for CI."""
        response = page.request.get(f"{api_base_url}/health", timeout=ci_timeout)
        assert response.status in [200, 503]
    
    @pytest.mark.playwright
    @pytest.mark.ci
    @pytest.mark.fast
    def test_response_time_ci(self, page, api_base_url, ci_timeout):
        """Fast response time check for CI."""
        start = time.time()
        response = page.request.get(f"{api_base_url}/health", timeout=ci_timeout)
        elapsed = time.time() - start
        
        assert response.status == 200
        assert elapsed < 3.0, f"Response too slow for CI: {elapsed:.3f}s"


class TestPlaywrightCICritical:
    """Critical path tests for CI."""
    
    @pytest.mark.playwright
    @pytest.mark.ci
    @pytest.mark.critical
    def test_critical_endpoints_ci(self, page, api_base_url, ci_timeout):
        """Test critical endpoints in CI."""
        critical_endpoints = ["/health"]
        
        for endpoint in critical_endpoints:
            response = page.request.get(
                f"{api_base_url}{endpoint}",
                timeout=ci_timeout
            )
            assert response.status == 200
    
    @pytest.mark.playwright
    @pytest.mark.ci
    @pytest.mark.critical
    def test_error_handling_ci(self, page, api_base_url, ci_timeout):
        """Test error handling in CI."""
        response = page.request.get(
            f"{api_base_url}/nonexistent_endpoint_xyz",
            timeout=ci_timeout
        )
        assert response.status in [404, 400]


class TestPlaywrightCIParallel:
    """Parallel tests for CI."""
    
    @pytest.mark.playwright
    @pytest.mark.ci
    @pytest.mark.parallel
    def test_parallel_health_checks_ci(self, browser, api_base_url, ci_timeout):
        """Parallel health checks for CI."""
        import concurrent.futures
        
        def make_request():
            context = browser.new_context()
            page = context.new_page()
            try:
                return page.request.get(f"{api_base_url}/health", timeout=ci_timeout)
            finally:
                page.close()
                context.close()
        
        with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
            futures = [executor.submit(make_request) for _ in range(10)]
            results = [future.result() for future in concurrent.futures.as_completed(futures)]
        
        assert len(results) == 10
        assert all(r.status == 200 for r in results)


class TestPlaywrightCIReporting:
    """CI reporting tests."""
    
    @pytest.mark.playwright
    @pytest.mark.ci
    def test_junit_xml_output(self, page, api_base_url):
        """Test that can generate JUnit XML."""
        response = page.request.get(f"{api_base_url}/health")
        assert response.status == 200
        # JUnit XML is generated by pytest with --junit-xml flag
    
    @pytest.mark.playwright
    @pytest.mark.ci
    def test_coverage_output(self, page, api_base_url):
        """Test that can generate coverage reports."""
        response = page.request.get(f"{api_base_url}/health")
        assert response.status == 200
        # Coverage is generated by pytest-cov with --cov flag



