optimized_deepseek:
  vocab_size: 1000
  hidden_size: 512
  num_layers: 6
  num_attention_heads: 8
  intermediate_size: 2048
  max_position_embeddings: 2048
  dropout: 0.1
  
  q_lora_rank: 256
  kv_lora_rank: 128
  qk_rope_head_dim: 64
  v_head_dim: 64
  
  n_routed_experts: 16
  n_shared_experts: 2
  n_activated_experts: 4
  
  use_flash_attention: true
  use_gradient_checkpointing: true
  use_optimized_moe: true
  use_memory_efficient_attention: true
  enable_advanced_optimizations: true
  enable_quantization: false
  enable_fp16: false
  enable_compilation: true
  enable_jit: false
  optimization_level: "aggressive"
  enable_kernel_fusion: true

optimized_viral_clipper:
  hidden_size: 512
  num_layers: 6
  num_attention_heads: 8
  dropout: 0.1
  max_sequence_length: 1000
  
  max_duration: 3600
  clip_duration: 30
  min_clip_duration: 10
  max_clip_duration: 60
  
  engagement_threshold: 0.8
  view_velocity_threshold: 1000
  comment_ratio_threshold: 0.05
  like_ratio_threshold: 0.1
  
  visual_feature_dim: 2048
  audio_feature_dim: 512
  text_feature_dim: 768
  engagement_feature_dim: 64
  
  use_flash_attention: true
  use_gradient_checkpointing: true
  use_efficient_fusion: true
  use_streaming_inference: true
  enable_advanced_optimizations: true
  enable_quantization: true
  enable_fp16: true
  enable_compilation: true
  optimization_level: "memory"
  enable_batch_optimization: true

optimized_brandkit:
  hidden_size: 768
  num_layers: 8
  num_attention_heads: 12
  dropout: 0.1
  max_sequence_length: 2048
  
  color_palette_size: 16
  typography_features: 64
  layout_features: 128
  tone_categories: 10
  sentiment_dim: 32
  style_dim: 64
  
  visual_feature_dim: 1024
  text_feature_dim: 768
  metadata_feature_dim: 256
  
  use_flash_attention: true
  use_gradient_checkpointing: true
  use_cached_embeddings: true
  use_efficient_cross_attention: true
  enable_advanced_optimizations: true
  enable_quantization: true
  enable_fp16: false
  enable_compilation: true
  optimization_level: "default"
  enable_cache_optimization: true

ultra_optimized_deepseek:
  hidden_size: 2048
  num_layers: 16
  num_heads: 16
  intermediate_size: 5504
  max_sequence_length: 4096
  enable_ultra_fusion: true
  enable_dynamic_batching: true
  enable_adaptive_precision: true
  enable_memory_pooling: true
  enable_compute_overlap: true
  enable_kernel_optimization: true
  enable_ultra_optimizations: true

ultra_optimized_viral_clipper:
  hidden_size: 512
  num_layers: 6
  num_heads: 8
  intermediate_size: 2048
  max_sequence_length: 1024
  enable_ultra_fusion: true
  enable_dynamic_batching: true
  enable_adaptive_precision: true
  enable_memory_pooling: true
  enable_compute_overlap: true
  enable_kernel_optimization: true

ultra_optimized_brandkit:
  hidden_size: 512
  num_layers: 4
  num_heads: 8
  intermediate_size: 1024
  max_sequence_length: 512
  enable_ultra_fusion: true
  enable_dynamic_batching: false
  enable_adaptive_precision: true
  enable_memory_pooling: true
  enable_compute_overlap: false
  enable_kernel_optimization: true

benchmark:
  warmup_runs: 3
  benchmark_runs: 10
  batch_sizes: [1, 2, 4, 8, 16]
  max_memory_mb: 8000
  save_results: true
  generate_report: true
