#!/usr/bin/env python3
"""
Requirements Optimizer
Removes unused dependencies and optimizes requirements files
"""

import re
import sys
from pathlib import Path
from collections import defaultdict
import subprocess


def get_imported_modules(directory='.'):
    """Find all imported modules in the codebase"""
    imported = set()
    
    for py_file in Path(directory).rglob('*.py'):
        if 'venv' in str(py_file) or '__pycache__' in str(py_file):
            continue
        
        try:
            with open(py_file, 'r', encoding='utf-8') as f:
                content = f.read()
                
                # Find imports
                import_patterns = [
                    r'^import\s+([a-zA-Z0-9_]+)',
                    r'^from\s+([a-zA-Z0-9_]+)',
                ]
                
                for line in content.split('\n'):
                    for pattern in import_patterns:
                        match = re.match(pattern, line.strip())
                        if match:
                            module = match.group(1).split('.')[0]
                            imported.add(module.lower())
        except Exception:
            pass
    
    return imported


def parse_requirements(filepath):
    """Parse requirements file"""
    requirements = []
    
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#') or line.startswith('-r'):
                continue
            
            # Extract package name
            package = line.split('>=')[0].split('==')[0].split('[')[0].strip()
            if package:
                requirements.append((package, line))
    
    return requirements


def check_package_usage(package_name, imported_modules):
    """Check if package is used in code"""
    # Map common package names to import names
    package_map = {
        'python-jose': 'jose',
        'python-multipart': 'multipart',
        'python-dotenv': 'dotenv',
        'python-dateutil': 'dateutil',
        'python-slugify': 'slugify',
        'opencv-python': 'cv2',
        'pillow': 'PIL',
        'scikit-learn': 'sklearn',
        'scikit-image': 'skimage',
    }
    
    import_name = package_map.get(package_name, package_name)
    import_name = import_name.replace('-', '_').lower()
    
    return import_name in imported_modules


def optimize_requirements_file(filepath, imported_modules):
    """Optimize a requirements file"""
    requirements = parse_requirements(filepath)
    used = []
    unused = []
    
    for package, line in requirements:
        if check_package_usage(package, imported_modules):
            used.append(line)
        else:
            unused.append((package, line))
    
    return used, unused


def main():
    """Main function"""
    if len(sys.argv) < 2:
        print("Usage: python optimize-requirements.py <requirements-file>")
        sys.exit(1)
    
    filepath = Path(sys.argv[1])
    if not filepath.exists():
        print(f"Error: {filepath} not found")
        sys.exit(1)
    
    print(f"Analyzing {filepath}...")
    print("Scanning codebase for imports...")
    
    imported_modules = get_imported_modules()
    print(f"Found {len(imported_modules)} imported modules")
    
    used, unused = optimize_requirements_file(filepath, imported_modules)
    
    print(f"\nResults for {filepath}:")
    print(f"  Used packages: {len(used)}")
    print(f"  Potentially unused: {len(unused)}")
    
    if unused:
        print("\n⚠️  Potentially unused packages:")
        for package, line in unused[:20]:  # Show first 20
            print(f"  - {package}")
        if len(unused) > 20:
            print(f"  ... and {len(unused) - 20} more")
        
        response = input("\nCreate optimized file? (y/n): ")
        if response.lower() == 'y':
            output_file = filepath.parent / f"{filepath.stem}-optimized{filepath.suffix}"
            with open(output_file, 'w') as f:
                f.write(f"# Optimized version of {filepath.name}\n")
                f.write(f"# Generated by optimize-requirements.py\n\n")
                for line in used:
                    f.write(line + '\n')
            print(f"✓ Optimized file created: {output_file}")
            print("⚠️  Review carefully before using!")


if __name__ == '__main__':
    main()



