# HeyGen AI System Configuration
# ==============================

# Database Configuration
database:
  host: localhost
  port: 5432
  name: heygen_ai
  user: postgres
  password: ""
  pool_size: 10
  max_overflow: 20
  echo: false

# Cache Configuration
cache:
  redis_url: redis://localhost:6379
  memory_limit: 1000
  ttl_seconds: 3600
  enable_compression: true
  compression_threshold: 1024

# API Configuration
api:
  host: 0.0.0.0
  port: 8000
  workers: 4
  timeout: 30
  max_requests: 1000
  cors_origins:
    - "*"

# Security Configuration
security:
  secret_key: "your-secret-key-change-in-production"
  algorithm: HS256
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7
  password_min_length: 8
  enable_rate_limiting: true
  max_requests_per_minute: 60

# Monitoring Configuration
monitoring:
  enable_health_checks: true
  health_check_interval: 30
  enable_metrics: true
  metrics_port: 9090
  enable_tracing: false
  log_level: INFO

# System Configuration
system:
  environment: development
  debug: true
  log_file: logs/heygen_ai.log
  max_log_size: 104857600  # 100MB
  backup_logs: 5
  temp_dir: temp
  data_dir: data
