# Enhanced Configuration for Frontier Model Training
# This configuration includes all advanced features and optimizations

# Environment Configuration
environment: "development"  # development, staging, production
version: "1.0.0"
description: "Enhanced Frontier Model Training Configuration"

# Dataset Configuration
dataset:
  name: "your_dataset"
  config: "your_config"
  train_split: "train"
  test_split: "test"
  cache_dir: "./data/cache"
  streaming: false

# Model Configuration
model:
  name: "deepseek-ai/deepseek-r1"
  use_deepspeed: false
  fp16: true
  bf16: false
  torch_dtype: "auto"
  attn_implementation: "flash_attention_2"
  trust_remote_code: true
  model_revision: null

# Training Parameters
training:
  batch_size: 8
  gradient_accumulation_steps: 1
  learning_rate: 5e-5
  max_steps: 1000
  warmup_ratio: 0.1
  weight_decay: 0.01
  max_grad_norm: 1.0
  lr_scheduler_type: "cosine"
  num_cycles: 1
  seed: 42
  output_dir: "./output"
  logging_steps: 10
  save_steps: 500
  eval_steps: 500
  eval_strategy: "steps"
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  report_to: ["tensorboard", "wandb"]

# Optimization Settings
optimization:
  use_amp: true
  use_gradient_checkpointing: true
  use_flash_attention: true
  use_8bit_optimizer: false
  use_cpu_offload: false
  use_activation_checkpointing: true
  use_attention_slicing: true
  use_sequence_parallelism: false

# Performance Settings
performance:
  use_cudnn_benchmark: true
  use_tf32: true
  use_channels_last: true
  use_compile: true

# DeepSpeed Configuration
deepspeed:
  use_deepspeed: false
  zero_stage: 2
  offload_optimizer: true
  offload_param: false
  gradient_clipping: 1.0
  fp16: true
  bf16: false
  config_file: null

# DeepSeek Specific Settings
deepseek:
  model_type: "deepseek"
  max_position_embeddings: 8192
  hidden_size: 4096
  num_hidden_layers: 32
  num_attention_heads: 32
  intermediate_size: 11008
  hidden_dropout_prob: 0.1
  attention_dropout_prob: 0.1
  layer_norm_eps: 1e-5
  use_rotary_embeddings: true
  use_alibi: false
  use_flash_attention_2: true
  use_sliding_window: true
  sliding_window_size: 4096

# Parallel Processing Settings
parallel:
  attention: true
  mlp: true
  layernorm: true
  embedding: true
  output: true
  residual: true
  ffn: true
  attention_output: true
  mlp_output: true
  layernorm_output: true
  embedding_output: true
  residual_output: true
  ffn_output: true
  attention_input: true
  mlp_input: true
  layernorm_input: true
  embedding_input: true
  residual_input: true
  ffn_input: true

# Kalman Filter Settings
kalman:
  process_noise: 0.01
  measurement_noise: 0.1
  memory_size: 1000

# Reward Functions
rewards:
  functions: ["accuracy", "format", "tag_count"]
  cosine_min_value_wrong: 0.0
  cosine_max_value_wrong: -0.5
  cosine_min_value_correct: 0.5
  cosine_max_value_correct: 1.0
  cosine_max_len: 1000
  repetition_n_grams: 3
  repetition_max_penalty: -1.0
  code_language: "python"

# Distributed Training Settings
distributed:
  backend: "nccl"
  world_size: -1
  rank: -1
  master_addr: "localhost"
  master_port: "29500"

# Monitoring and Logging
monitoring:
  use_wandb: true
  use_mlflow: false
  use_tensorboard: true
  log_level: "INFO"
  log_file: "./logs/training.log"
  metrics_log_interval: 10
  checkpoint_interval: 500
  enable_sentry: false
  sentry_dsn: null

# Performance Monitoring
performance_monitoring:
  enable_monitoring: true
  monitoring_interval: 5.0
  enable_profiling: false
  profiling_activities: ["cpu", "cuda"]
  alert_thresholds:
    memory_usage:
      warning: 80.0
      error: 90.0
      critical: 95.0
    gpu_memory:
      warning: 80.0
      error: 90.0
      critical: 95.0
    gpu_utilization:
      warning: 90.0
      error: 95.0
      critical: 98.0
    cpu_usage:
      warning: 80.0
      error: 90.0
      critical: 95.0
    batch_time:
      warning: 10.0
      error: 20.0
      critical: 30.0
    training_loss:
      warning: 10.0
      error: 20.0
      critical: 50.0

# Testing Configuration
testing:
  enable_testing: true
  test_dir: "./tests"
  output_dir: "./test_results"
  enable_coverage: true
  enable_html_report: true
  enable_parallel: true
  max_workers: 4
  test_suites:
    - name: "unit_tests"
      test_type: "unit"
      timeout: 60
      parallel: true
      max_workers: 2
    - name: "integration_tests"
      test_type: "integration"
      timeout: 300
      parallel: false
      max_workers: 1
    - name: "performance_tests"
      test_type: "performance"
      timeout: 600
      parallel: false
      max_workers: 1

# Deployment Configuration
deployment:
  deployment_type: "docker"  # local, docker, kubernetes, cloud
  image_name: "frontier-model"
  image_tag: "latest"
  replicas: 1
  cpu_limit: "2"
  memory_limit: "4Gi"
  cpu_request: "1"
  memory_request: "2Gi"
  gpu_enabled: false
  gpu_count: 0
  ports: [8080]
  environment_vars:
    ENVIRONMENT: "development"
    LOG_LEVEL: "INFO"
  volumes:
    - name: "data"
      mount_path: "/app/data"
      host_path: "./data"
    - name: "logs"
      mount_path: "/app/logs"
      host_path: "./logs"
    - name: "models"
      mount_path: "/app/models"
      host_path: "./models"
  health_check:
    enabled: true
    path: "/health"
    interval: 30
    timeout: 10
    retries: 3
  auto_scaling:
    enabled: false
    min_replicas: 1
    max_replicas: 10
    target_cpu_utilization: 70
    target_memory_utilization: 80

# CI/CD Configuration
cicd:
  pipeline_name: "frontier-model-ci"
  trigger_branches: ["main", "develop"]
  build_stages: ["test", "build"]
  test_stages: ["unit", "integration", "performance"]
  deploy_stages: ["staging", "production"]
  notification_channels: ["admin@example.com"]
  artifact_registry: "your-registry.com"
  deployment_targets: ["staging", "production"]
  platforms: ["github", "gitlab", "jenkins"]

# Security Configuration
security:
  enable_encryption: true
  encryption_key: null  # Will be generated if null
  enable_audit_logging: true
  enable_access_control: false
  allowed_users: []
  api_key_required: false
  rate_limiting:
    enabled: false
    requests_per_minute: 100

# Backup and Recovery
backup:
  enable_backup: true
  backup_interval: "24h"
  backup_retention_days: 30
  backup_location: "./backups"
  include_logs: true
  include_models: true
  include_configs: true

# Advanced Features
advanced:
  enable_experimental_features: false
  custom_loss_functions: []
  custom_optimizers: []
  custom_schedulers: []
  enable_model_compression: false
  compression_ratio: 0.5
  enable_quantization: false
  quantization_bits: 8
  enable_pruning: false
  pruning_ratio: 0.1
