# AI Document Processor - Refactored Configuration
# ================================================
# Modern YAML configuration with comprehensive settings

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8001
  workers: 1
  reload: false
  access_log: true
  cors_origins: ["*"]

# Database Configuration
database:
  url: null  # Set via DATABASE_URL environment variable
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600

# Cache Configuration
cache:
  enabled: true
  backend: "memory"  # memory, redis, disk
  redis_url: null  # Set via REDIS_URL environment variable
  max_memory_mb: 1024
  default_ttl: 3600
  compression: true

# AI Service Configuration
ai:
  provider: "openai"  # openai, anthropic, cohere, local
  api_key: null  # Set via AI_API_KEY environment variable
  model: "gpt-3.5-turbo"
  max_tokens: 2000
  temperature: 0.7
  timeout: 30
  retry_attempts: 3
  retry_delay: 1.0

# Document Processing Configuration
processing:
  max_file_size_mb: 100
  allowed_extensions: [".md", ".pdf", ".docx", ".doc", ".txt", ".html", ".xml"]
  max_workers: 8
  chunk_size: 8192
  enable_streaming: true
  enable_parallel: true
  enable_ai_classification: true
  enable_ai_transformation: true
  timeout_seconds: 300
  retry_attempts: 3
  priority: "normal"  # low, normal, high, urgent
  custom_settings: {}

# Security Configuration
security:
  enable_rate_limiting: true
  rate_limit_requests: 100
  rate_limit_window: 60
  enable_authentication: false
  secret_key: null  # Set via SECRET_KEY environment variable
  allowed_origins: ["*"]

# Monitoring and Logging Configuration
monitoring:
  log_level: "INFO"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  enable_metrics: true
  metrics_port: 9090
  enable_tracing: false
  jaeger_endpoint: null  # Set via JAEGER_ENDPOINT environment variable

# Performance Optimization
performance:
  enable_uvloop: true
  enable_compression: true
  enable_caching: true
  cache_ttl: 3600
  max_concurrent_requests: 1000
  request_timeout: 30

# File Handling
files:
  temp_dir: "/tmp"
  max_temp_files: 1000
  cleanup_interval: 3600
  enable_compression: true
  compression_level: 6

# API Configuration
api:
  version: "v1"
  title: "AI Document Processor API"
  description: "Ultra-fast AI document processing with modern architecture"
  contact:
    name: "AI Document Processor Team"
    email: "support@example.com"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"

# Development Settings
development:
  debug: false
  reload: false
  log_requests: true
  enable_cors: true
  enable_docs: true

# Production Settings
production:
  debug: false
  reload: false
  log_requests: true
  enable_cors: false
  enable_docs: false
  enable_metrics: true
  enable_tracing: true

















