version: '3.8'

services:
  ai-document-processor:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAX_FILE_SIZE=52428800
      - MIN_CONFIDENCE_THRESHOLD=0.5
      - ENABLE_AI_CLASSIFICATION=true
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ai-document-processor/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ai_document_processor
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ai_document_processor"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
  postgres_data:


