version: '3.8'

services:
  ai-document-classifier:
    build: .
    ports:
      - "8001:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./templates:/app/templates
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ai-document-classifier/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-classifier-network

  # Optional: Add a reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ai-document-classifier
    restart: unless-stopped
    networks:
      - ai-classifier-network

networks:
  ai-classifier-network:
    driver: bridge

volumes:
  templates:
  logs:



























