---
apiVersion: v1
kind: Namespace
metadata:
  name: truthgpt-optimization
  labels:
    name: truthgpt-optimization
    environment: production
    team: ml-engineering
    cost-center: ai-research
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: truthgpt-resource-quota
  namespace: truthgpt-optimization
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: truthgpt-limit-range
  namespace: truthgpt-optimization
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      storage: "100Gi"
    min:
      storage: "1Gi"
    type: PersistentVolumeClaim


