---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: truthgpt-logs-pvc
  namespace: truthgpt-optimization
  labels:
    app: truthgpt-optimization
    component: logs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-csi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: truthgpt-cache-pvc
  namespace: truthgpt-optimization
  labels:
    app: truthgpt-optimization
    component: cache
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: azurefile-csi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: truthgpt-models-pvc
  namespace: truthgpt-optimization
  labels:
    app: truthgpt-optimization
    component: models
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile-csi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: truthgpt-data-pvc
  namespace: truthgpt-optimization
  labels:
    app: truthgpt-optimization
    component: data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: azurefile-csi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
  namespace: truthgpt-optimization
  labels:
    app: prometheus
    component: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: managed-csi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
  namespace: truthgpt-optimization
  labels:
    app: grafana
    component: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-csi
  volumeMode: Filesystem


