"""
Constants for Lovable Community SAM3.
"""

from .api_constants import (
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    MIN_PAGE_SIZE,
    DEFAULT_LIMIT,
    MAX_LIMIT,
    TRENDING_PERIODS,
    SORT_OPTIONS,
    SHARE_PLATFORMS,
    REPORT_TYPES,
    REPORT_STATUSES,
    MAX_EXPORT_CHATS,
    MAX_EXPORT_COMMENTS,
    MAX_EXPORT_VOTES,
    MAX_EXPORT_BOOKMARKS,
    MAX_TAG_CHATS_LIMIT,
    DEFAULT_TAG_LIMIT,
    DEFAULT_TRENDING_TAG_LIMIT,
    MAX_RANKING_CHATS_LIMIT,
    MAX_REMIXES_LIMIT,
    MAX_FOLLOWING_LIMIT,
    MAX_TITLE_LENGTH,
    MAX_DESCRIPTION_LENGTH,
    MAX_USER_ID_LENGTH,
    MAX_CHAT_ID_LENGTH,
    MAX_TAG_LENGTH,
    MAX_COMMENT_LENGTH
)

__all__ = [
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "MIN_PAGE_SIZE",
    "DEFAULT_LIMIT",
    "MAX_LIMIT",
    "TRENDING_PERIODS",
    "SORT_OPTIONS",
    "SHARE_PLATFORMS",
    "REPORT_TYPES",
    "REPORT_STATUSES",
    "MAX_EXPORT_CHATS",
    "MAX_EXPORT_COMMENTS",
    "MAX_EXPORT_VOTES",
    "MAX_EXPORT_BOOKMARKS",
    "MAX_TAG_CHATS_LIMIT",
    "DEFAULT_TAG_LIMIT",
    "DEFAULT_TRENDING_TAG_LIMIT",
    "MAX_RANKING_CHATS_LIMIT",
    "MAX_REMIXES_LIMIT",
    "MAX_FOLLOWING_LIMIT",
    "MAX_TITLE_LENGTH",
    "MAX_DESCRIPTION_LENGTH",
    "MAX_USER_ID_LENGTH",
    "MAX_CHAT_ID_LENGTH",
    "MAX_TAG_LENGTH",
    "MAX_TAG_LENGTH",
    "MAX_COMMENT_LENGTH",
    "SIMULATED_SCREENSHOT_PATH",
    "TASK_TYPE_WEB",
    "TASK_TYPE_MOBILE",
]

# Pipeline Constants
SIMULATED_SCREENSHOT_PATH = "simulated_web_result.png"
TASK_TYPE_WEB = "WEB_TASK"
TASK_TYPE_MOBILE = "MOBILE_TASK"






