# Gamma App - Prometheus Configuration
# Monitoring configuration for metrics collection

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Gamma App API
  - job_name: 'gamma_app'
    static_configs:
      - targets: ['gamma_app:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Gamma App Health Check
  - job_name: 'gamma_app_health'
    static_configs:
      - targets: ['gamma_app:8000']
    metrics_path: '/health'
    scrape_interval: 30s

  # Node Exporter (if available)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 15s

  # Redis Exporter (if available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 15s

  # PostgreSQL Exporter (if available)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 15s

  # Nginx Exporter (if available)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']
    scrape_interval: 15s



























