# Gamma App - Default Configuration
# This is the base configuration file

environment: development
debug: true

# Database Configuration
database:
  url: "sqlite:///./gamma_app.db"
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600
  echo: false
  echo_pool: false

# Redis Configuration
redis:
  url: "redis://localhost:6379"
  max_connections: 10
  socket_timeout: 5
  socket_connect_timeout: 5
  retry_on_timeout: true
  health_check_interval: 30

# AI Configuration
ai:
  openai_api_key: null
  anthropic_api_key: null
  default_model: "gpt-3.5-turbo"
  max_tokens: 4000
  temperature: 0.7
  timeout: 30
  retry_attempts: 3
  enable_local_models: true
  local_models_dir: "models"
  quantization: false

# Security Configuration
security:
  secret_key: "your-super-secret-key-change-this-in-production"
  jwt_algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7
  password_min_length: 8
  require_strong_password: true
  enable_2fa: false
  rate_limit_requests: 100
  rate_limit_window: 3600
  max_login_attempts: 5
  lockout_duration: 900
  allowed_ips: []
  blocked_ips: []
  enable_csrf: true
  enable_cors: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8000"

# Cache Configuration
cache:
  default_ttl: 3600
  max_memory: "100mb"
  compression: true
  serialization: "json"
  key_prefix: "gamma_app"
  enable_local_cache: true
  local_cache_size: 1000

# Performance Configuration
performance:
  enable_memory_profiling: true
  enable_cpu_profiling: true
  enable_request_tracking: true
  enable_database_monitoring: true
  enable_cache_monitoring: true
  sampling_rate: 1.0
  alert_thresholds:
    response_time: 5.0
    memory_usage: 80.0
    cpu_usage: 90.0
    error_rate: 5.0
    disk_usage: 90.0
  retention_days: 7
  max_metrics_per_minute: 1000

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/gamma_app.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5
  enable_json_logging: false
  enable_structured_logging: true

# Monitoring Configuration
monitoring:
  enable_prometheus: true
  prometheus_port: 9090
  enable_health_checks: true
  health_check_interval: 30
  enable_metrics_endpoint: true
  metrics_path: "/metrics"
  enable_tracing: false
  tracing_endpoint: null

# Export Configuration
export:
  max_file_size: 104857600  # 100MB
  supported_formats:
    - "pdf"
    - "pptx"
    - "html"
    - "markdown"
    - "json"
    - "png"
    - "zip"
  temp_dir: "temp"
  output_dir: "exports"
  enable_compression: true
  compression_level: 6
  max_concurrent_exports: 5

# Collaboration Configuration
collaboration:
  max_sessions: 100
  max_users_per_session: 10
  session_timeout: 3600
  enable_real_time: true
  websocket_timeout: 30
  enable_typing_indicators: true
  enable_cursor_tracking: true
  enable_comment_system: true



























