"""
Requirements Optimizer - Optimizador de archivos requirements.txt
=================================================================

Herramienta para optimizar, validar y mejorar archivos de requirements.txt
con detección de duplicados, conflictos y mejores prácticas.
"""

import logging
import re
from typing import Dict, List, Optional, Set, Tuple, Any
from pathlib import Path
from collections import defaultdict
import hashlib

logger = logging.getLogger(__name__)


class RequirementsOptimizer:
    """Optimizador de archivos requirements.txt"""
    
    def __init__(self, requirements_file: Path):
        """
        Inicializar optimizador.
        
        Args:
            requirements_file: Ruta al archivo requirements.txt
        """
        self.requirements_file = Path(requirements_file)
        self.lines: List[str] = []
        self.packages: Dict[str, List[str]] = defaultdict(list)
        self.comments: Dict[int, str] = {}
        self._load_file()
    
    def _load_file(self) -> None:
        """Cargar archivo requirements.txt"""
        if not self.requirements_file.exists():
            raise FileNotFoundError(f"Requirements file not found: {self.requirements_file}")
        
        with open(self.requirements_file, "r", encoding="utf-8") as f:
            self.lines = f.readlines()
        
        self._parse_packages()
    
    def _parse_packages(self) -> None:
        """Parsear paquetes del archivo"""
        for line_num, line in enumerate(self.lines):
            original_line = line
            line = line.strip()
            
            if not line or line.startswith("#"):
                if line.startswith("#"):
                    self.comments[line_num] = line
                continue
            
            if line.startswith("-r") or line.startswith("--requirement"):
                continue
            
            package_match = re.match(r"^([a-zA-Z0-9_-]+(?:\[[^\]]+\])?)(.*)$", line)
            if package_match:
                package_name = package_match.group(1)
                version_spec = package_match.group(2).strip()
                
                base_name = package_name.split("[")[0]
                self.packages[base_name.lower()].append({
                    "line_num": line_num,
                    "original": original_line.rstrip(),
                    "name": base_name,
                    "full_name": package_name,
                    "version": version_spec,
                    "comment": self.comments.get(line_num - 1, "")
                })
    
    def find_duplicates(self) -> List[Dict[str, Any]]:
        """
        Encontrar paquetes duplicados.
        
        Returns:
            Lista de duplicados encontrados
        """
        duplicates = []
        
        for package_name, occurrences in self.packages.items():
            if len(occurrences) > 1:
                duplicates.append({
                    "package": package_name,
                    "count": len(occurrences),
                    "occurrences": occurrences
                })
        
        return duplicates
    
    def find_conflicts(self) -> List[Dict[str, Any]]:
        """
        Encontrar conflictos de versiones.
        
        Returns:
            Lista de conflictos encontrados
        """
        conflicts = []
        
        for package_name, occurrences in self.packages.items():
            if len(occurrences) > 1:
                versions = [occ["version"] for occ in occurrences]
                if len(set(versions)) > 1:
                    conflicts.append({
                        "package": package_name,
                        "versions": versions,
                        "occurrences": occurrences
                    })
        
        return conflicts
    
    def optimize(self, output_file: Optional[Path] = None) -> Path:
        """
        Optimizar archivo requirements.txt.
        
        Args:
            output_file: Archivo de salida (default: requirements_optimized.txt)
        
        Returns:
            Ruta al archivo generado
        """
        output_file = output_file or self.requirements_file.parent / "requirements_optimized.txt"
        
        optimized_lines = []
        seen_packages: Set[str] = set()
        
        for package_name, occurrences in sorted(self.packages.items()):
            if package_name.lower() in seen_packages:
                continue
            
            best_occurrence = self._select_best_version(occurrences)
            if best_occurrence:
                optimized_lines.append(best_occurrence["original"])
                seen_packages.add(package_name.lower())
        
        with open(output_file, "w", encoding="utf-8") as f:
            f.write("# Optimized Requirements File\n")
            f.write("# Generated by RequirementsOptimizer\n\n")
            for line in optimized_lines:
                f.write(line + "\n")
        
        logger.info(f"Optimized requirements written to {output_file}")
        return output_file
    
    def _select_best_version(self, occurrences: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
        """Seleccionar la mejor versión entre múltiples ocurrencias"""
        if not occurrences:
            return None
        
        if len(occurrences) == 1:
            return occurrences[0]
        
        versions = [occ["version"] for occ in occurrences]
        if len(set(versions)) == 1:
            return occurrences[0]
        
        most_specific = max(occurrences, key=lambda x: len(x["version"]))
        return most_specific
    
    def validate(self) -> Tuple[bool, List[str]]:
        """
        Validar archivo requirements.txt.
        
        Returns:
            Tupla (is_valid, issues)
        """
        issues = []
        is_valid = True
        
        duplicates = self.find_duplicates()
        if duplicates:
            is_valid = False
            for dup in duplicates:
                issues.append(
                    f"Duplicate package '{dup['package']}' found {dup['count']} times"
                )
        
        conflicts = self.find_conflicts()
        if conflicts:
            is_valid = False
            for conflict in conflicts:
                issues.append(
                    f"Version conflict for '{conflict['package']}': {', '.join(conflict['versions'])}"
                )
        
        return is_valid, issues
    
    def generate_report(self) -> Dict[str, Any]:
        """
        Generar reporte de optimización.
        
        Returns:
            Diccionario con reporte completo
        """
        duplicates = self.find_duplicates()
        conflicts = self.find_conflicts()
        is_valid, issues = self.validate()
        
        total_packages = len(self.packages)
        duplicate_count = len(duplicates)
        conflict_count = len(conflicts)
        
        return {
            "file": str(self.requirements_file),
            "is_valid": is_valid,
            "summary": {
                "total_packages": total_packages,
                "duplicates": duplicate_count,
                "conflicts": conflict_count,
                "issues": len(issues)
            },
            "duplicates": duplicates,
            "conflicts": conflicts,
            "issues": issues,
            "recommendations": self._generate_recommendations(duplicates, conflicts)
        }
    
    def _generate_recommendations(
        self,
        duplicates: List[Dict[str, Any]],
        conflicts: List[Dict[str, Any]]
    ) -> List[str]:
        """Generar recomendaciones"""
        recommendations = []
        
        if duplicates:
            recommendations.append(
                f"Remove {len(duplicates)} duplicate package(s) to reduce file size"
            )
        
        if conflicts:
            recommendations.append(
                f"Resolve {len(conflicts)} version conflict(s) for consistency"
            )
        
        if not duplicates and not conflicts:
            recommendations.append("Requirements file is well-optimized!")
        
        return recommendations

