"""
HTML export handler.
"""

from typing import Dict, Any
from jinja2 import Template

from .base import BaseExporter


class HTMLExporter(BaseExporter):
    """HTML export handler with responsive design."""
    
    def get_supported_features(self) -> list:
        """Get supported HTML features."""
        return [
            "Web ready",
            "Responsive",
            "Interactive elements",
            "SEO friendly",
            "CSS styling",
            "JavaScript support",
            "Cross-browser compatibility"
        ]
    
    async def export(
        self, 
        content: Dict[str, Any], 
        config: Any, 
        output_path: str
    ) -> Dict[str, Any]:
        """Export content to HTML format."""
        try:
            # Preprocess content
            processed_content = self.preprocess_content(content)
            
            # Create HTML template
            html_template = """
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>{{ title }}</title>
                <style>
                    body {
                        font-family: Calibri, Arial, sans-serif;
                        font-size: 11px;
                        line-height: 1.15;
                        color: #2E2E2E;
                        max-width: 800px;
                        margin: 0 auto;
                        padding: 20px;
                        background-color: #ffffff;
                    }
                    h1, h2, h3 {
                        color: #1F4E79;
                        margin-top: 30px;
                        margin-bottom: 15px;
                    }
                    h1 {
                        font-size: 24px;
                        text-align: center;
                        border-bottom: 2px solid #1F4E79;
                        padding-bottom: 10px;
                    }
                    h2 {
                        font-size: 18px;
                    }
                    h3 {
                        font-size: 14px;
                    }
                    .header {
                        text-align: center;
                        margin-bottom: 30px;
                    }
                    .section {
                        margin-bottom: 20px;
                    }
                    p {
                        text-align: justify;
                        margin-bottom: 10px;
                    }
                    .metadata {
                        font-size: 10px;
                        color: #666;
                        margin-top: 30px;
                        padding-top: 20px;
                        border-top: 1px solid #ddd;
                    }
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>{{ title }}</h1>
                </div>
                {% for section in sections %}
                <div class="section">
                    {% if section.heading %}
                    <h2>{{ section.heading }}</h2>
                    {% endif %}
                    {% if section.content %}
                    <p>{{ section.content }}</p>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="metadata">
                    <p>Generated by Export IA - {{ timestamp }}</p>
                </div>
            </body>
            </html>
            """
            
            template = Template(html_template)
            html_content = template.render(
                title=processed_content.get("title", "Document"),
                sections=processed_content.get("sections", []),
                timestamp=processed_content.get("exported_at", "")
            )
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(html_content)
            
            result = {
                "format": "html",
                "sections": len(processed_content.get("sections", [])),
                "professional_features": {
                    "responsive": True,
                    "seo_friendly": True,
                    "interactive_elements": True
                }
            }
            
            return self.postprocess_result(result)
            
        except Exception as e:
            self.logger.error(f"HTML export failed: {e}")
            raise
    
    def postprocess_result(self, result: Dict[str, Any]) -> Dict[str, Any]:
        """Postprocess HTML export result."""
        result["file_type"] = "text/html"
        result["mime_type"] = "text/html"
        return result




