"""API routers for organizing endpoints"""
from fastapi import APIRouter

# Create routers for different feature groups
conversion_router = APIRouter(prefix="/convert", tags=["Conversion"])
format_router = APIRouter(prefix="/formats", tags=["Formats"])
cache_router = APIRouter(prefix="/cache", tags=["Cache"])
metrics_router = APIRouter(prefix="/metrics", tags=["Metrics"])
template_router = APIRouter(prefix="/templates", tags=["Templates"])
language_router = APIRouter(prefix="/languages", tags=["Languages"])
validation_router = APIRouter(prefix="/validate", tags=["Validation"])
compression_router = APIRouter(prefix="/compress", tags=["Compression"])
security_router = APIRouter(prefix="/security", tags=["Security"])
version_router = APIRouter(prefix="/version", tags=["Versioning"])
backup_router = APIRouter(prefix="/backup", tags=["Backup"])
annotation_router = APIRouter(prefix="/annotations", tags=["Annotations"])
collaboration_router = APIRouter(prefix="/collaboration", tags=["Collaboration"])
search_router = APIRouter(prefix="/search", tags=["Search"])
notification_router = APIRouter(prefix="/notifications", tags=["Notifications"])
analytics_router = APIRouter(prefix="/analytics", tags=["Analytics"])
batch_router = APIRouter(prefix="/batch", tags=["Batch"])
plugin_router = APIRouter(prefix="/plugins", tags=["Plugins"])
scheduler_router = APIRouter(prefix="/scheduler", tags=["Scheduler"])
permission_router = APIRouter(prefix="/permissions", tags=["Permissions"])
dashboard_router = APIRouter(prefix="/dashboard", tags=["Dashboard"])
comparison_router = APIRouter(prefix="/compare", tags=["Comparison"])
translation_router = APIRouter(prefix="/translate", tags=["Translation"])
signature_router = APIRouter(prefix="/sign", tags=["Signatures"])
export_router = APIRouter(prefix="/export", tags=["Export"])
workflow_router = APIRouter(prefix="/workflow", tags=["Workflow"])
ai_router = APIRouter(prefix="/ai", tags=["AI"])
cloud_router = APIRouter(prefix="/cloud", tags=["Cloud"])
review_router = APIRouter(prefix="/review", tags=["Review"])
integration_router = APIRouter(prefix="/integrations", tags=["Integrations"])
webhook_router = APIRouter(prefix="/webhooks", tags=["Webhooks"])
pipeline_router = APIRouter(prefix="/pipeline", tags=["Pipelines"])
test_router = APIRouter(prefix="/tests", tags=["Testing"])
rate_limit_router = APIRouter(prefix="/rate-limit", tags=["Rate Limiting"])
health_router = APIRouter(prefix="/health", tags=["Health"])
config_router = APIRouter(prefix="/config", tags=["Configuration"])
queue_router = APIRouter(prefix="/queue", tags=["Task Queue"])
auth_router = APIRouter(prefix="/auth", tags=["Authentication"])
audit_router = APIRouter(prefix="/audit", tags=["Audit"])
image_router = APIRouter(prefix="/images", tags=["Images"])
preview_router = APIRouter(prefix="/preview", tags=["Preview"])
watermark_router = APIRouter(prefix="/watermark", tags=["Watermark"])

