"""
GitHub Integration - Integración con GitHub
===========================================

Funcionalidades para crear repositorios en GitHub automáticamente.
"""

import logging
from typing import Optional, Dict, Any
from pathlib import Path
import subprocess
import json

logger = logging.getLogger(__name__)


class GitHubIntegration:
    """Integración con GitHub para crear repositorios automáticamente"""

    def __init__(self, github_token: Optional[str] = None):
        """
        Inicializa la integración con GitHub.

        Args:
            github_token: Token de GitHub (opcional, puede estar en .env)
        """
        self.github_token = github_token
        self.github_username = None

    async def create_repository(
        self,
        project_name: str,
        description: str,
        private: bool = False,
        auto_init: bool = True,
    ) -> Dict[str, Any]:
        """
        Crea un repositorio en GitHub.

        Args:
            project_name: Nombre del repositorio
            description: Descripción del repositorio
            private: Si el repositorio es privado
            auto_init: Si inicializar con README

        Returns:
            Información del repositorio creado
        """
        try:
            import httpx

            if not self.github_token:
                raise ValueError("GitHub token no configurado")

            url = "https://api.github.com/user/repos"
            headers = {
                "Authorization": f"token {self.github_token}",
                "Accept": "application/vnd.github.v3+json",
            }
            data = {
                "name": project_name,
                "description": description,
                "private": private,
                "auto_init": auto_init,
            }

            async with httpx.AsyncClient() as client:
                response = await client.post(url, headers=headers, json=data)
                response.raise_for_status()
                repo_data = response.json()

                return {
                    "success": True,
                    "repository_url": repo_data.get("html_url"),
                    "clone_url": repo_data.get("clone_url"),
                    "ssh_url": repo_data.get("ssh_url"),
                    "full_name": repo_data.get("full_name"),
                }

        except ImportError:
            logger.warning("httpx no está instalado, usando git CLI")
            return await self._create_repo_with_git(project_name, description, private)
        except Exception as e:
            logger.error(f"Error creando repositorio en GitHub: {e}")
            return {"success": False, "error": str(e)}

    async def _create_repo_with_git(
        self, project_name: str, description: str, private: bool
    ) -> Dict[str, Any]:
        """Crea repositorio usando git CLI"""
        try:
            # Verificar si git está instalado
            result = subprocess.run(
                ["git", "--version"], capture_output=True, text=True
            )
            if result.returncode != 0:
                return {"success": False, "error": "Git no está instalado"}

            return {
                "success": True,
                "message": "Usa 'gh repo create' o crea el repo manualmente en GitHub",
            }
        except Exception as e:
            return {"success": False, "error": str(e)}

    async def push_to_github(
        self, project_dir: Path, repo_url: str, branch: str = "main"
    ) -> Dict[str, Any]:
        """
        Hace push del proyecto a GitHub.

        Args:
            project_dir: Directorio del proyecto
            repo_url: URL del repositorio
            branch: Rama a usar

        Returns:
            Resultado de la operación
        """
        try:
            import subprocess

            # Inicializar git si no existe
            if not (project_dir / ".git").exists():
                subprocess.run(
                    ["git", "init"],
                    cwd=project_dir,
                    check=True,
                    capture_output=True,
                )

            # Agregar remote
            subprocess.run(
                ["git", "remote", "add", "origin", repo_url],
                cwd=project_dir,
                check=False,
                capture_output=True,
            )

            # Agregar todos los archivos
            subprocess.run(
                ["git", "add", "."],
                cwd=project_dir,
                check=True,
                capture_output=True,
            )

            # Commit inicial
            subprocess.run(
                ["git", "commit", "-m", "Initial commit: Generated by AI Project Generator"],
                cwd=project_dir,
                check=True,
                capture_output=True,
            )

            # Push
            subprocess.run(
                ["git", "push", "-u", "origin", branch],
                cwd=project_dir,
                check=True,
                capture_output=True,
            )

            return {"success": True, "message": "Proyecto subido a GitHub exitosamente"}

        except subprocess.CalledProcessError as e:
            logger.error(f"Error haciendo push a GitHub: {e}")
            return {"success": False, "error": str(e)}
        except Exception as e:
            logger.error(f"Error inesperado: {e}")
            return {"success": False, "error": str(e)}


